use crate::rpc::{ProcedureKind, RawContractSpec};

// Extracted once from the final legacy router type graph; maintained by the Rust API.
pub const FULL_CONTRACT: &[RawContractSpec] = &[
    RawContractSpec {
        path: "admin.databases.backups.createNow",
        kind: ProcedureKind::Mutation,
        input_ts: "{ databaseId: string; kind?: undefined | \"manual\" | \"auto\"; }",
        output_ts: "{ id: string; databaseId: string; kind: \"manual\" | \"auto\"; state: \"processing\" | \"uploaded\" | \"failed\"; objectKey: null | string; sizeBytes: null | number; error: null | string; createdAt: Date; completedAt: null | Date; }",
    },
    RawContractSpec {
        path: "admin.databases.backups.downloadUrl",
        kind: ProcedureKind::Query,
        input_ts: "{ backupId: string; expiresInSec?: undefined | number; }",
        output_ts: "{ backup: { id: string; databaseId: string; kind: \"manual\" | \"auto\"; state: \"processing\" | \"uploaded\" | \"failed\"; objectKey: null | string; sizeBytes: null | number; error: null | string; createdAt: Date; completedAt: null | Date; }; downloadUrl: string; }",
    },
    RawContractSpec {
        path: "admin.databases.backups.list",
        kind: ProcedureKind::Query,
        input_ts: "{ databaseId: string; includeFailed?: undefined | false | true; }",
        output_ts: "{ id: string; databaseId: string; kind: \"manual\" | \"auto\"; state: \"processing\" | \"uploaded\" | \"failed\"; objectKey: null | string; sizeBytes: null | number; error: null | string; createdAt: Date; completedAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "admin.databases.backups.restore",
        kind: ProcedureKind::Mutation,
        input_ts: "{ backupId: string; targetDatabaseId?: undefined | null | string; }",
        output_ts: "{ backupId: string; targetDatabaseId: string; }",
    },
    RawContractSpec {
        path: "admin.databases.backups.upload",
        kind: ProcedureKind::Mutation,
        input_ts: "{ databaseId: string; fileName: string; fileBase64: string; }",
        output_ts: "{ id: string; databaseId: string; kind: \"manual\" | \"auto\"; state: \"processing\" | \"uploaded\" | \"failed\"; objectKey: null | string; sizeBytes: null | number; error: null | string; createdAt: Date; completedAt: null | Date; }",
    },
    RawContractSpec {
        path: "admin.databases.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ hostId: string; name: string; username?: undefined | null | string; retentionDaily?: undefined | number; retentionWeekly?: undefined | number; retentionMonthly?: undefined | number; retentionYearly?: undefined | number; }",
        output_ts: "{ id: string; hostId: string; name: string; username: string; password: string; }",
    },
    RawContractSpec {
        path: "admin.databases.forkFromBackup",
        kind: ProcedureKind::Mutation,
        input_ts: "{ backupId: string; name: string; hostId?: undefined | null | string; username?: undefined | null | string; retentionDaily?: undefined | null | number; retentionWeekly?: undefined | null | number; retentionMonthly?: undefined | null | number; retentionYearly?: undefined | null | number; }",
        output_ts: "{ id: string; hostId: string; name: string; username: string; password: string; restoredFromBackupId: string; }",
    },
    RawContractSpec {
        path: "admin.databases.hosts.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; connectionDetails: { host: string; adminUsername: string; adminPassword: string; port?: undefined | number; adminDatabase?: undefined | string; }; backupDetails?: undefined | { enabled?: undefined | false | true; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; publicBaseUrl?: undefined | null | string; forcePathStyle?: undefined | false | true; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; keyPrefix?: undefined | null | string; }; }",
        output_ts: "{ id: string; name: string; connectionDetails: { host: string; port: number; adminDatabase: string; adminUsername: string; adminPassword: string; }; backupDetails: { enabled: boolean; forcePathStyle: boolean; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; publicBaseUrl?: undefined | null | string; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; keyPrefix?: undefined | null | string; }; createdAt: Date; updatedAt: Date; }",
    },
    RawContractSpec {
        path: "admin.databases.hosts.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ hostId: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.databases.hosts.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ id: string; name: string; connectionDetails: { host: string; port: number; adminDatabase: string; adminUsername: string; adminPassword: string; }; backupDetails: { enabled: boolean; forcePathStyle: boolean; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; publicBaseUrl?: undefined | null | string; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; keyPrefix?: undefined | null | string; }; createdAt: Date; updatedAt: Date; }[]",
    },
    RawContractSpec {
        path: "admin.databases.hosts.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ hostId: string; data: { name?: undefined | null | string; connectionDetails?: undefined | null | { host: string; adminUsername: string; adminPassword: string; port?: undefined | number; adminDatabase?: undefined | string; }; backupDetails?: undefined | null | { enabled?: undefined | false | true; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; publicBaseUrl?: undefined | null | string; forcePathStyle?: undefined | false | true; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; keyPrefix?: undefined | null | string; }; }; }",
        output_ts: "{ id: string; name: string; connectionDetails: { host: string; port: number; adminDatabase: string; adminUsername: string; adminPassword: string; }; backupDetails: { enabled: boolean; forcePathStyle: boolean; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; publicBaseUrl?: undefined | null | string; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; keyPrefix?: undefined | null | string; }; createdAt: Date; updatedAt: Date; }",
    },
    RawContractSpec {
        path: "admin.databases.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ id: string; hostId: string; hostName: string; name: string; username: string; retentionDaily: number; retentionWeekly: number; retentionMonthly: number; retentionYearly: number; createdAt: Date; updatedAt: Date; }[]",
    },
    RawContractSpec {
        path: "admin.databases.rotateCredentials",
        kind: ProcedureKind::Mutation,
        input_ts: "{ databaseId: string; }",
        output_ts: "{ id: string; username: string; password: string; }",
    },
    RawContractSpec {
        path: "admin.databases.updateRetention",
        kind: ProcedureKind::Mutation,
        input_ts: "{ databaseId: string; data: { retentionDaily: number; retentionWeekly: number; retentionMonthly: number; retentionYearly: number; }; }",
        output_ts: "{ id: string; retentionDaily: number; retentionWeekly: number; retentionMonthly: number; retentionYearly: number; }",
    },
    RawContractSpec {
        path: "admin.errors.list",
        kind: ProcedureKind::Query,
        input_ts: "undefined | void | { tenant?: undefined | null | string; limit?: undefined | number; }",
        output_ts: "{ tenant: string; id: string; level: \"error\" | \"warning\"; source: string; message: string; stack: null | string; path: null | string; componentStack: null | string; metadata: null | Record<string, unknown>; userAgent: null | string; createdByUserId: null | string; username: null | string; createdAt: Date; }[]",
    },
    RawContractSpec {
        path: "admin.login",
        kind: ProcedureKind::Mutation,
        input_ts: "{ password: string; tenant?: undefined | null | string; }",
        output_ts: "{ token: string; }",
    },
    RawContractSpec {
        path: "admin.tenants.activate",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; contact_details: { email: string; companyName?: undefined | null | string; address?: undefined | null | { city?: undefined | null | string; zip?: undefined | null | string; country?: undefined | null | string; streetAddress?: undefined | null | string; }; }; options?: undefined | { sso: { \"ms-entra-id\": { enabled: boolean; importUserUsername: boolean; importUserName: boolean; importUserEmail: boolean; tenantId?: undefined | null | string; clientId?: undefined | null | string; objectId?: undefined | null | string; }; }; }; connection_details?: undefined | { postgresDSN?: undefined | null | string; postgresDatabaseId?: undefined | null | string; objectStorage?: undefined | null | { enabled?: undefined | false | true; provider?: undefined | \"s3\"; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; forcePathStyle?: undefined | false | true; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; publicBaseUrl?: undefined | null | string; keyPrefix?: undefined | null | string; uploadUrlTtlSec?: undefined | number; downloadUrlTtlSec?: undefined | number; }; }; }",
        output_ts: "{ adminPassword: string; }",
    },
    RawContractSpec {
        path: "admin.tenants.deactivate",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.deleteForever",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.get",
        kind: ProcedureKind::Query,
        input_ts: "{ name: string; }",
        output_ts: "{ name: string; locked_at: null | Date; deleted_at: null | Date; deactivated_at: null | Date; connection_details: { postgresDSN?: undefined | null | string; postgresDatabaseId?: undefined | null | string; objectStorage?: undefined | null | { enabled: boolean; provider: \"s3\"; forcePathStyle: boolean; uploadUrlTtlSec: number; downloadUrlTtlSec: number; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; publicBaseUrl?: undefined | null | string; keyPrefix?: undefined | null | string; }; }; contact_details: { email: string; companyName?: undefined | null | string; address?: undefined | null | { city?: undefined | null | string; zip?: undefined | null | string; country?: undefined | null | string; streetAddress?: undefined | null | string; }; }; options: { sso: { \"ms-entra-id\": { enabled: boolean; importUserUsername: boolean; importUserName: boolean; importUserEmail: boolean; tenantId?: undefined | null | string; clientId?: undefined | null | string; objectId?: undefined | null | string; }; }; }; }",
    },
    RawContractSpec {
        path: "admin.tenants.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ name: string; locked_at: null | Date; deleted_at: null | Date; deactivated_at: null | Date; connection_details: { postgresDSN?: undefined | null | string; postgresDatabaseId?: undefined | null | string; objectStorage?: undefined | null | { enabled: boolean; provider: \"s3\"; forcePathStyle: boolean; uploadUrlTtlSec: number; downloadUrlTtlSec: number; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; publicBaseUrl?: undefined | null | string; keyPrefix?: undefined | null | string; }; }; contact_details: { email: string; companyName?: undefined | null | string; address?: undefined | null | { city?: undefined | null | string; zip?: undefined | null | string; country?: undefined | null | string; streetAddress?: undefined | null | string; }; }; options: { sso: { \"ms-entra-id\": { enabled: boolean; importUserUsername: boolean; importUserName: boolean; importUserEmail: boolean; tenantId?: undefined | null | string; clientId?: undefined | null | string; objectId?: undefined | null | string; }; }; }; }[]",
    },
    RawContractSpec {
        path: "admin.tenants.lock",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.undelete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.unlock",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.tenants.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; data: { contact_details?: undefined | { email: string; companyName?: undefined | null | string; address?: undefined | null | { city?: undefined | null | string; zip?: undefined | null | string; country?: undefined | null | string; streetAddress?: undefined | null | string; }; }; connection_details?: undefined | { postgresDSN?: undefined | null | string; postgresDatabaseId?: undefined | null | string; objectStorage?: undefined | null | { enabled?: undefined | false | true; provider?: undefined | \"s3\"; bucket?: undefined | null | string; region?: undefined | null | string; endpoint?: undefined | null | string; forcePathStyle?: undefined | false | true; accessKeyId?: undefined | null | string; secretAccessKey?: undefined | null | string; sessionToken?: undefined | null | string; publicBaseUrl?: undefined | null | string; keyPrefix?: undefined | null | string; uploadUrlTtlSec?: undefined | number; downloadUrlTtlSec?: undefined | number; }; }; options?: undefined | { sso: { \"ms-entra-id\": { enabled: boolean; importUserUsername: boolean; importUserName: boolean; importUserEmail: boolean; tenantId?: undefined | null | string; clientId?: undefined | null | string; objectId?: undefined | null | string; }; }; }; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "admin.users.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ tenant: string; username: string; firstName: string; lastName?: undefined | null | string; email?: undefined | null | string; phone?: undefined | null | string; salutation?: undefined | null | string; contractType?: undefined | null | \"internal\" | \"external\" | \"subcontractor\"; password?: undefined | null | string; }",
        output_ts: "{ userId: string; password: string; }",
    },
    RawContractSpec {
        path: "admin.users.list",
        kind: ProcedureKind::Query,
        input_ts: "{ tenant: string; search?: undefined | null | string; includeArchived?: undefined | false | true; }",
        output_ts: "{ id: string; username: string; firstName: string; lastName: null | string; email: null | string; deactivatedAt: null | Date; archivedAt: null | Date; isAdmin: boolean; }[]",
    },
    RawContractSpec {
        path: "admin.users.resetPassword",
        kind: ProcedureKind::Mutation,
        input_ts: "{ tenant: string; userId: string; password?: undefined | null | string; }",
        output_ts: "{ password: string; }",
    },
    RawContractSpec {
        path: "admin.users.setAdmin",
        kind: ProcedureKind::Mutation,
        input_ts: "{ tenant: string; userId: string; admin: boolean; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "auth.check",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "auth.login",
        kind: ProcedureKind::Mutation,
        input_ts: "{ tenant: string; username: string; password: string; }",
        output_ts: "{ token: string; }",
    },
    RawContractSpec {
        path: "auth.logout",
        kind: ProcedureKind::Mutation,
        input_ts: "void",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "auth.passkeys.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "auth.passkeys.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ id: string; label: string; createdAt: Date; lastUsedAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "auth.passkeys.login",
        kind: ProcedureKind::Mutation,
        input_ts: "{ challengeToken: string; credential: { id: string; rawId: string; type: \"public-key\"; response: { clientDataJSON: string; authenticatorData: string; signature: string; userHandle?: undefined | null | string; }; }; }",
        output_ts: "{ token: string; }",
    },
    RawContractSpec {
        path: "auth.passkeys.loginOptions",
        kind: ProcedureKind::Mutation,
        input_ts: "undefined | void | { tenant: string; username: string; }",
        output_ts: "{ challengeToken: string; options: { challenge: string; rpId: string; allowCredentials: { id: string; type: \"public-key\"; transports?: undefined | string[]; }[]; timeout: number; userVerification: \"required\"; }; }",
    },
    RawContractSpec {
        path: "auth.passkeys.register",
        kind: ProcedureKind::Mutation,
        input_ts: "{ challengeToken: string; label: string; credential: { id: string; rawId: string; type: \"public-key\"; response: { clientDataJSON: string; attestationObject: string; }; transports?: undefined | string[]; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "auth.passkeys.registerOptions",
        kind: ProcedureKind::Mutation,
        input_ts: "void",
        output_ts: "{ challengeToken: string; options: { challenge: string; rp: { name: string; id: string; }; user: { id: string; name: string; displayName: string; }; pubKeyCredParams: { type: \"public-key\"; alg: number; }[]; timeout: number; attestation: \"none\"; authenticatorSelection: { residentKey: \"required\"; requireResidentKey: true; userVerification: \"required\"; }; excludeCredentials: { id: string; type: \"public-key\"; transports?: undefined | string[]; }[]; }; }",
    },
    RawContractSpec {
        path: "auth.sessionInfo",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ user: { id: string; username: string; salutation: null | string; firstName: string; lastName: null | string; contractType: \"internal\" | \"external\" | \"subcontractor\"; phone: null | string; email: null | string; locale: \"de\" | \"en\"; }; session: { id: string; inetAddr: null | string; userAgent: null | string; createdAt: Date; expiresAt: Date; }; roles: (\":admin\" | \":llm\" | \"view:users\" | \"manage:users\" | \"delete:users\" | \"view:projects\" | \"manage:projects\" | \"delete:projects\" | \"view:projectDeployments\" | \"manage:projectDeployments\" | \"delete:projectDeployments\" | \"view:userVacations\" | \"manage:userVacations\" | \"delete:userVacations\" | \"view:tools\" | \"manage:tools\" | \"delete:tools\" | \"view:toolTrackings\" | \"manage:toolTrackings\" | \"delete:toolTrackings\" | \"view:toolInventories\" | \"manage:toolInventories\" | \"delete:toolInventories\" | \"view:products\" | \"manage:products\" | \"delete:products\" | \"view:deliveryNotes\" | \"manage:deliveryNotes\" | \"delete:deliveryNotes\" | \"view:productVendors\" | \"manage:productVendors\" | \"delete:productVendors\" | \"view:productPriceRecords\" | \"manage:productPriceRecords\" | \"delete:productPriceRecords\" | \"view:customers\" | \"manage:customers\" | \"delete:customers\" | \"view:contacts\" | \"manage:contacts\" | \"delete:contacts\" | \"view:dailyProjectReports\" | \"manage:dailyProjectReports\" | \"delete:dailyProjectReports\" | \"view:regieReports\" | \"manage:regieReports\" | \"delete:regieReports\" | \"view:clientScripts\" | \"manage:clientScripts\" | \"delete:clientScripts\")[]; tenant: { companyName: null | string; objectStorageEnabled: boolean; }; }",
    },
    RawContractSpec {
        path: "auth.setPassword",
        kind: ProcedureKind::Mutation,
        input_ts: "{ username: string; password: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "clientScripts.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; code: string; description?: undefined | null | string; enabled?: undefined | false | true; }",
        output_ts: "{ id: string; name: string; description: null | string; code: string; enabled: boolean; createdByUserId: null | string; modifiedByUserId: null | string; createdAt: Date; modifiedAt: Date; }",
    },
    RawContractSpec {
        path: "clientScripts.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "clientScripts.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "null | { id: string; name: string; description: null | string; code: string; enabled: boolean; createdByUserId: null | string; modifiedByUserId: null | string; createdAt: Date; modifiedAt: Date; }",
    },
    RawContractSpec {
        path: "clientScripts.list",
        kind: ProcedureKind::Query,
        input_ts: "undefined | void | { search?: undefined | null | string; includeDisabled?: undefined | false | true; limit?: undefined | number; }",
        output_ts: "{ id: string; name: string; description: null | string; enabled: boolean; createdByUserId: null | string; modifiedByUserId: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "clientScripts.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { name?: undefined | string; description?: undefined | null | string; code?: undefined | string; enabled?: undefined | false | true; }; }",
        output_ts: "null | { id: string; name: string; description: null | string; code: string; enabled: boolean; createdByUserId: null | string; modifiedByUserId: null | string; createdAt: Date; modifiedAt: Date; }",
    },
    RawContractSpec {
        path: "contacts.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ salutation?: undefined | null | string; firstName?: undefined | null | string; lastName?: undefined | null | string; address?: undefined | null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers?: undefined | { number: string; name?: undefined | null | string; }[]; emailAddresses?: undefined | { email: string; name?: undefined | null | string; }[]; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "contacts.customers.list",
        kind: ProcedureKind::Query,
        input_ts: "{ contactId: string; }",
        output_ts: "{ id: string; salutation: null | string; name: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "contacts.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "contacts.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; salutation: null | string; firstName: null | string; lastName: null | string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdAt: Date; modifiedAt: Date; }",
    },
    RawContractSpec {
        path: "contacts.list",
        kind: ProcedureKind::Query,
        input_ts: "{ search?: undefined | null | string; }",
        output_ts: "{ id: string; salutation: null | string; firstName: null | string; lastName: null | string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "contacts.projects.list",
        kind: ProcedureKind::Query,
        input_ts: "{ contactId: string; }",
        output_ts: "{ id: string; title: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; customerId: null | string; responsibleProjectLeaderUserId: null | string; orderReceivedAt: null | Date; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; finishedAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "contacts.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { salutation?: undefined | null | string; firstName?: undefined | null | string; lastName?: undefined | null | string; address?: undefined | null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers?: undefined | { number: string; name?: undefined | null | string; }[]; emailAddresses?: undefined | { email: string; name?: undefined | null | string; }[]; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "customers.contacts.add",
        kind: ProcedureKind::Mutation,
        input_ts: "{ customerId: string; contactId: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "customers.contacts.list",
        kind: ProcedureKind::Query,
        input_ts: "{ customerId: string; }",
        output_ts: "{ id: string; salutation: null | string; firstName: null | string; lastName: null | string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "customers.contacts.remove",
        kind: ProcedureKind::Mutation,
        input_ts: "{ customerId: string; contactId: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "customers.contacts.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ customerId: string; contactIds: string[]; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "customers.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; salutation?: undefined | null | string; address?: undefined | null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers?: undefined | { number: string; name?: undefined | null | string; }[]; emailAddresses?: undefined | { email: string; name?: undefined | null | string; }[]; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "customers.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "customers.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; salutation: null | string; name: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; }",
    },
    RawContractSpec {
        path: "customers.list",
        kind: ProcedureKind::Query,
        input_ts: "{ search?: undefined | null | string; }",
        output_ts: "{ id: string; salutation: null | string; name: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "customers.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { salutation?: undefined | null | string; name?: undefined | string; address?: undefined | null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers?: undefined | { number: string; name?: undefined | null | string; }[]; emailAddresses?: undefined | { email: string; name?: undefined | null | string; }[]; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "deliveryNotes.costs.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ noteId: string; totalCost: number; records: { recordId: string; productId: string; quantity: number; priceRecord: null | { id: string; productId: string; vendorId: null | string; timestamp: Date; price: number; isRealPurchase: boolean; comment: null | string; }; }[]; specialRecords: { recordId: string; name: string; unit: string; amount: number; pricePerUnit: null | number; comment: null | string; totalCost: number; }[]; }",
    },
    RawContractSpec {
        path: "deliveryNotes.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; effectiveTimestamp?: undefined | null | Date; comment?: undefined | null | string; records?: undefined | { productId: string; quantity: number; unit?: undefined | null | string; comment?: undefined | null | string; }[]; specialRecords?: undefined | { name: string; unit: string; amount: number; pricePerUnit: null | number; comment?: undefined | null | string; }[]; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "deliveryNotes.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "deliveryNotes.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; } | { autoId: unknown; }",
        output_ts: "{ id: string; autoId: number; projectId: string; comment: null | string; createdByUserId: null | string; createdAt: Date; effectiveTimestamp: Date; records: { id: string; noteId: string; productId: string; quantity: number; unit: string; comment: null | string; }[]; specialRecords: { id: string; noteId: string; name: string; unit: string; amount: number; pricePerUnit: null | number; comment: null | string; }[]; }",
    },
    RawContractSpec {
        path: "deliveryNotes.list",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId?: undefined | null | string; createdByUserId?: undefined | null | string; }",
        output_ts: "{ id: string; autoId: number; projectId: string; comment: null | string; createdByUserId: null | string; createdAt: Date; effectiveTimestamp: Date; records: { id: string; noteId: string; productId: string; quantity: number; unit: string; comment: null | string; }[]; specialRecords: { id: string; noteId: string; name: string; unit: string; amount: number; pricePerUnit: null | number; comment: null | string; }[]; }[]",
    },
    RawContractSpec {
        path: "deliveryNotes.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { projectId?: undefined | null | string; effectiveTimestamp?: undefined | null | Date; comment?: undefined | null | string; records?: undefined | null | { productId: string; quantity: number; unit?: undefined | null | string; comment?: undefined | null | string; }[]; specialRecords?: undefined | null | { name: string; unit: string; amount: number; pricePerUnit: null | number; comment?: undefined | null | string; }[]; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "errorReports.report",
        kind: ProcedureKind::Mutation,
        input_ts: "{ source: string; message: string; level?: undefined | \"error\" | \"warning\"; stack?: undefined | null | string; path?: undefined | null | string; componentStack?: undefined | null | string; metadata?: undefined | null | Record<string, unknown>; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "personalization.actions.append",
        kind: ProcedureKind::Mutation,
        input_ts: "{ actionId: string; label: string; href?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "personalization.actions.list",
        kind: ProcedureKind::Query,
        input_ts: "undefined | void | { limit?: undefined | number; }",
        output_ts: "{ id: string; actionId: string; label: string; href: null | string; usedAt: Date; }[]",
    },
    RawContractSpec {
        path: "personalization.activity.list",
        kind: ProcedureKind::Query,
        input_ts: "undefined | void | { limit?: undefined | number; resourceType?: undefined | null | \"user\" | \"customer\" | \"project\" | \"contact\" | \"product\" | \"tool\" | \"productVendor\" | \"deliveryNote\" | \"regieReport\" | \"dailyProjectReport\"; resourceId?: undefined | null | string; contextId?: undefined | null | string; includeProjectContext?: undefined | false | true; }",
        output_ts: "{ resourceType: \"user\" | \"customer\" | \"project\" | \"contact\" | \"product\" | \"tool\" | \"productVendor\" | \"deliveryNote\" | \"regieReport\" | \"dailyProjectReport\"; resourceId: string; contextId: null | string; contextTitle: null | string; contextDate: null | Date; title: string; description: null | string; action: \"created\" | \"updated\"; occurredAt: Date; createdAt: Date; modifiedAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "personalization.visits.append",
        kind: ProcedureKind::Mutation,
        input_ts: "{ path: string; title?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "personalization.visits.list",
        kind: ProcedureKind::Query,
        input_ts: "undefined | void | { limit?: undefined | number; }",
        output_ts: "{ id: string; path: string; title: null | string; visitedAt: Date; }[]",
    },
    RawContractSpec {
        path: "ping",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "string",
    },
    RawContractSpec {
        path: "products.brands.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "string[]",
    },
    RawContractSpec {
        path: "products.categories.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "string[]",
    },
    RawContractSpec {
        path: "products.categories.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; categories: string[]; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.categories.tag",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; category: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.categories.untag",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; category: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ customId: number; name: string; baseUnit: string; brand?: undefined | null | string; description?: undefined | null | string; otherUnits?: undefined | Record<string, number>; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "products.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; customId: number; name: string; description: null | string; brand: null | string; baseUnit: string; otherUnits: Record<string, number>; categories: string[]; }",
    },
    RawContractSpec {
        path: "products.list",
        kind: ProcedureKind::Query,
        input_ts: "{ category?: undefined | null | string; search?: undefined | null | string; }",
        output_ts: "{ id: string; customId: number; name: string; description: null | string; brand: null | string; baseUnit: string; otherUnits: Record<string, number>; categories: string[]; }[]",
    },
    RawContractSpec {
        path: "products.priceRecords.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ productId: string; pricePerBaseUnit: number; timestamp: Date; isRealPurchase: boolean; vendorId?: undefined | null | string; comment?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "products.priceRecords.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.priceRecords.list",
        kind: ProcedureKind::Query,
        input_ts: "{ productId?: undefined | null | string; vendorId?: undefined | null | string; isRealPurchase?: undefined | null | false | true; }",
        output_ts: "{ id: string; productId: string; vendorId: null | string; timestamp: Date; price: number; isRealPurchase: boolean; comment: null | string; }[]",
    },
    RawContractSpec {
        path: "products.priceRecords.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { productId?: undefined | string; vendorId?: undefined | null | string; pricePerBaseUnit?: undefined | number; timestamp?: undefined | Date; isRealPurchase?: undefined | false | true; comment?: undefined | null | string; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.suggestNextCustomId",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "number",
    },
    RawContractSpec {
        path: "products.units.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "string[]",
    },
    RawContractSpec {
        path: "products.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { customId?: undefined | number; name?: undefined | string; brand?: undefined | null | string; description?: undefined | null | string; baseUnit?: undefined | string; otherUnits?: undefined | Record<string, number>; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.vendors.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ name: string; description?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "products.vendors.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "products.vendors.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; name: string; description: null | string; createdAt: Date; modifiedAt: Date; }",
    },
    RawContractSpec {
        path: "products.vendors.list",
        kind: ProcedureKind::Query,
        input_ts: "{ search?: undefined | null | string; }",
        output_ts: "{ id: string; name: string; description: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "products.vendors.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { name?: undefined | string; description?: undefined | null | string; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.contacts.add",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; contactId: string; label?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.contacts.list",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId: string; }",
        output_ts: "{ label: null | string; id: string; salutation: null | string; firstName: null | string; lastName: null | string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; phoneNumbers: { number: string; name?: undefined | null | string; }[]; emailAddresses: { email: string; name?: undefined | null | string; }[]; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "projects.contacts.remove",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; contactId: string; label?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.contacts.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; contacts: { contactId: string; label?: undefined | null | string; }[]; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.costs.entries.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; type: \"offer\" | \"invoice\"; amount: number; comment?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.costs.entries.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.costs.entries.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; id: string; data: { amount: number; comment?: undefined | null | string; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.costs.filterOptions",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ finishingYears: number[]; projectLeaders: { id: string; firstName: string; lastName: null | string; }[]; }",
    },
    RawContractSpec {
        path: "projects.costs.get",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId: string; from?: unknown; to?: unknown; }",
        output_ts: "{ offers: { id: string; projectId: string; type: \"offer\" | \"invoice\"; amount: number; comment: null | string; createdByUserId: null | string; createdAt: Date; }[]; invoices: { id: string; projectId: string; type: \"offer\" | \"invoice\"; amount: number; comment: null | string; createdByUserId: null | string; createdAt: Date; }[]; deliveryNotes: { noteId: string; autoId: number; effectiveTimestamp: Date; totalCost: number; }[]; products: { productId: string; quantity: number; totalCost: number; priceRecord: null | { id: string; productId: string; vendorId: null | string; timestamp: Date; price: number; isRealPurchase: boolean; comment: null | string; }; }[]; specialRecords: { id: string; noteId: string; noteAutoId: number; effectiveTimestamp: Date; name: string; unit: string; amount: number; pricePerUnit: null | number; comment: null | string; totalCost: number; }[]; workHours: { id: string; userId: null | string; day: Date; hours: number; costPerHour: null | number; contractType: \"internal\" | \"external\" | \"subcontractor\"; totalCost: number; }[]; subcontractorWorkHours: { id: string; userId: null | string; day: Date; hours: number; costPerHour: null | number; contractType: \"internal\" | \"external\" | \"subcontractor\"; totalCost: number; }[]; toolTrackings: { id: string; toolId: string; responsibleUserId: null | string; startedByUserId: null | string; endedByUserId: null | string; toolUsageCostPerDay: null | number; comment: null | string; startedAt: Date; endedAt: null | Date; deadlineAt: null | Date; totalCost: number; }[]; commonCosts: { fgk: { baseCost: number; overheadCost: number; totalCost: number; }; mgk: { baseCost: number; overheadCost: number; totalCost: number; }; ngk: { baseCost: number; overheadCost: number; totalCost: number; }; overallOverhead: number; }; totalCosts: { offers: number; invoices: number; deliveryNotes: number; products: number; specialRecords: number; workHours: number; subcontractorWorkHours: number; toolTrackings: number; overall: number; }; }",
    },
    RawContractSpec {
        path: "projects.costs.overview",
        kind: ProcedureKind::Query,
        input_ts: "undefined | void | { status?: undefined | \"finished\" | \"active\" | \"all\"; closingYear?: undefined | null | number; responsibleProjectLeaderUserId?: undefined | null | string; }",
        output_ts: "{ projectId: string; title: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; costs: number; offersTotal: number; invoicesTotal: number; gainOrLoss: null | number; hasInvoices: boolean; finishedAt: null | Date; responsibleProjectLeaderUserId: null | string; }[]",
    },
    RawContractSpec {
        path: "projects.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ title: string; address?: undefined | null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; customerId?: undefined | null | string; responsibleProjectLeaderUserId?: undefined | null | string; orderReceivedAt?: undefined | null | Date; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "projects.dailyReports.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; day: unknown; summary?: undefined | null | string; weather?: undefined | null | { summary?: undefined | null | string; temperatureC?: undefined | null | number; precipitationMm?: undefined | null | number; windKph?: undefined | null | number; }; workHours?: undefined | { hours: number; costPerHour: null | number; userId?: undefined | null | string; contractType?: undefined | null | \"internal\" | \"external\" | \"subcontractor\"; }[]; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.dailyReports.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; day: unknown; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.dailyReports.get",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId: string; day: unknown; }",
        output_ts: "{ id: string; projectId: string; day: Date; summary: null | string; weather: null | { summary?: undefined | null | string; temperatureC?: undefined | null | number; precipitationMm?: undefined | null | number; windKph?: undefined | null | number; }; createdByUserId: null | string; createdAt: Date; workHours: { id: string; reportId: string; userId: null | string; hours: number; costPerHour: null | number; contractType: \"internal\" | \"external\" | \"subcontractor\"; }[]; photos: { id: string; projectId: string; fileName: string; mimeType: string; kind: \"file\" | \"image\"; sizeBytes: null | number; status: \"uploaded\" | \"pending\"; thumbnailStatus: \"none\" | \"processing\" | \"failed\" | \"queued\" | \"ready\"; thumbnailExpiresAt: null | Date; previewExpiresAt: null | Date; thumbnailWidth: null | number; thumbnailHeight: null | number; createdByUserId: null | string; createdAt: Date; uploadedAt: null | Date; downloadExpiresAt: null | Date; downloadAttachmentExpiresAt: null | Date; thumbnailUrl?: undefined | null | string; previewUrl?: undefined | null | string; downloadUrl?: undefined | null | string; downloadAttachmentUrl?: undefined | null | string; }[]; }",
    },
    RawContractSpec {
        path: "projects.dailyReports.list",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId?: undefined | null | string; from?: unknown; to?: unknown; limit?: undefined | number; offset?: undefined | number; }",
        output_ts: "{ id: string; projectId: string; day: Date; summary: null | string; weather: null | { summary?: undefined | null | string; temperatureC?: undefined | null | number; precipitationMm?: undefined | null | number; windKph?: undefined | null | number; }; createdByUserId: null | string; createdAt: Date; workHours: { id: string; reportId: string; userId: null | string; hours: number; costPerHour: null | number; contractType: \"internal\" | \"external\" | \"subcontractor\"; }[]; photos: { id: string; projectId: string; fileName: string; mimeType: string; kind: \"file\" | \"image\"; sizeBytes: null | number; status: \"uploaded\" | \"pending\"; thumbnailStatus: \"none\" | \"processing\" | \"failed\" | \"queued\" | \"ready\"; thumbnailExpiresAt: null | Date; previewExpiresAt: null | Date; thumbnailWidth: null | number; thumbnailHeight: null | number; createdByUserId: null | string; createdAt: Date; uploadedAt: null | Date; downloadExpiresAt: null | Date; downloadAttachmentExpiresAt: null | Date; thumbnailUrl?: undefined | null | string; previewUrl?: undefined | null | string; downloadUrl?: undefined | null | string; downloadAttachmentUrl?: undefined | null | string; }[]; }[]",
    },
    RawContractSpec {
        path: "projects.dailyReports.photos.add",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; day: unknown; fileId: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.dailyReports.photos.remove",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; day: unknown; fileId: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.dailyReports.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; day: unknown; data: { day?: unknown; summary?: undefined | null | string; weather?: undefined | null | { summary?: undefined | null | string; temperatureC?: undefined | null | number; precipitationMm?: undefined | null | number; windKph?: undefined | null | number; }; workHours?: undefined | null | { hours: number; costPerHour: null | number; userId?: undefined | null | string; contractType?: undefined | null | \"internal\" | \"external\" | \"subcontractor\"; }[]; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.deployments.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; userId: string; from: unknown; to: unknown; note?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "projects.deployments.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.deployments.list",
        kind: ProcedureKind::Query,
        input_ts: "{ from: unknown; to: unknown; since?: unknown; projectId?: undefined | null | string; userId?: undefined | null | string; }",
        output_ts: "{ id: string; projectId: string; userId: string; from: Date; to: Date; note: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "projects.deployments.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { projectId?: undefined | null | string; userId?: undefined | null | string; from?: unknown; to?: unknown; note?: undefined | null | string; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.files.completeUpload",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; fileId: string; etag?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.files.createUpload",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; fileName: string; mimeType: string; sizeBytes?: undefined | null | number; }",
        output_ts: "{ fileId: string; objectKey: string; uploadUrl: string; uploadMethod: \"PUT\"; uploadHeaders: Record<string, string>; expiresAt: Date; }",
    },
    RawContractSpec {
        path: "projects.files.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; fileId: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.files.list",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId: string; }",
        output_ts: "{ id: string; projectId: string; fileName: string; mimeType: string; kind: \"file\" | \"image\"; sizeBytes: null | number; status: \"uploaded\" | \"pending\"; thumbnailStatus: \"none\" | \"processing\" | \"failed\" | \"queued\" | \"ready\"; thumbnailExpiresAt: null | Date; previewExpiresAt: null | Date; thumbnailWidth: null | number; thumbnailHeight: null | number; createdByUserId: null | string; createdAt: Date; uploadedAt: null | Date; downloadExpiresAt: null | Date; downloadAttachmentExpiresAt: null | Date; thumbnailUrl?: undefined | null | string; previewUrl?: undefined | null | string; downloadUrl?: undefined | null | string; downloadAttachmentUrl?: undefined | null | string; }[]",
    },
    RawContractSpec {
        path: "projects.finish",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; title: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; customerId: null | string; responsibleProjectLeaderUserId: null | string; orderReceivedAt: null | Date; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; finishedAt: null | Date; }",
    },
    RawContractSpec {
        path: "projects.list",
        kind: ProcedureKind::Query,
        input_ts: "{ search?: undefined | null | string; finished?: undefined | null | false | true; customerId?: undefined | null | string; }",
        output_ts: "{ id: string; title: string; address: null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; customerId: null | string; responsibleProjectLeaderUserId: null | string; orderReceivedAt: null | Date; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; finishedAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "projects.resume",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.unavailability.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; from: unknown; to: unknown; reason: string; note?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "projects.unavailability.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.unavailability.list",
        kind: ProcedureKind::Query,
        input_ts: "{ from?: unknown; to?: unknown; projectId?: undefined | null | string; }",
        output_ts: "{ id: string; projectId: string; from: Date; to: Date; reason: string; note: null | string; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "projects.unavailability.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { projectId?: undefined | null | string; from?: unknown; to?: unknown; reason?: undefined | null | string; note?: undefined | null | string; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "projects.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { title?: undefined | string; address?: undefined | null | { city: string; streetAddress: string; country?: undefined | null | string; zip?: undefined | null | string; }; customerId?: undefined | null | string; responsibleProjectLeaderUserId?: undefined | null | string; orderReceivedAt?: undefined | null | Date; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "regieReports.costs.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ reportId: string; totalCost: number; products: { recordId: string; productId: string; quantity: number; priceRecord: null | { id: string; productId: string; vendorId: null | string; timestamp: Date; price: number; isRealPurchase: boolean; comment: null | string; }; }[]; specialRecords: { recordId: string; name: string; unit: string; amount: number; comment: null | string; }[]; workHours: { recordId: string; userId: null | string; day: Date; hours: number; }[]; }",
    },
    RawContractSpec {
        path: "regieReports.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ projectId: string; day: string; summary?: undefined | null | string; products?: undefined | { productId: string; quantity: number; comment?: undefined | null | string; }[]; specialRecords?: undefined | { name: string; unit: string; amount: number; comment?: undefined | null | string; }[]; workHours?: undefined | { day: string; hours: number; userId?: undefined | null | string; }[]; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "regieReports.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "regieReports.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; projectId: string; day: Date; summary: null | string; createdByUserId: string; createdAt: Date; autoId: number; products: { id: string; reportId: string; productId: string; quantity: number; comment: null | string; }[]; specialRecords: { id: string; reportId: string; name: string; unit: string; amount: number; comment: null | string; }[]; workHours: { id: string; reportId: string; userId: null | string; day: Date; hours: number; }[]; }",
    },
    RawContractSpec {
        path: "regieReports.list",
        kind: ProcedureKind::Query,
        input_ts: "{ projectId?: undefined | null | string; dayFrom?: undefined | string; dayTo?: undefined | string; limit?: undefined | number; offset?: undefined | number; }",
        output_ts: "{ id: string; projectId: string; day: Date; summary: null | string; createdByUserId: string; createdAt: Date; autoId: number; products: { id: string; reportId: string; productId: string; quantity: number; comment: null | string; }[]; specialRecords: { id: string; reportId: string; name: string; unit: string; amount: number; comment: null | string; }[]; workHours: { id: string; reportId: string; userId: null | string; day: Date; hours: number; }[]; }[]",
    },
    RawContractSpec {
        path: "regieReports.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { day?: undefined | string; summary?: undefined | null | string; products?: undefined | null | { productId: string; quantity: number; comment?: undefined | null | string; }[]; specialRecords?: undefined | null | { name: string; unit: string; amount: number; comment?: undefined | null | string; }[]; workHours?: undefined | null | { day: string; hours: number; userId?: undefined | null | string; }[]; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "remarks.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ resourceType: \"customer\" | \"project\" | \"contact\" | \"tool\"; resourceId: string; body: string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "remarks.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "remarks.list",
        kind: ProcedureKind::Query,
        input_ts: "{ resourceType: \"customer\" | \"project\" | \"contact\" | \"tool\"; resourceId: string; }",
        output_ts: "{ id: string; body: string; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; }[]",
    },
    RawContractSpec {
        path: "remarks.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; body: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.costs.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ type: \"fgk\" | \"mgk\" | \"ngk\"; effectiveAt: unknown; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.costs.get",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ fgk: { type: \"fgk\" | \"mgk\" | \"ngk\"; effectiveAt: Date; relativeFactor: number; constant: number; }; mgk: { type: \"fgk\" | \"mgk\" | \"ngk\"; effectiveAt: Date; relativeFactor: number; constant: number; }; ngk: { type: \"fgk\" | \"mgk\" | \"ngk\"; effectiveAt: Date; relativeFactor: number; constant: number; }; history: { id: string; type: \"fgk\" | \"mgk\" | \"ngk\"; effectiveAt: Date; relativeFactor: number; constant: number; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; }[]; productOverheadFactor: number; workHourOverheadFactor: number; specialRecordOverheadFactor: number; toolOverheadFactor: number; }",
    },
    RawContractSpec {
        path: "settings.costs.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ type: \"fgk\" | \"mgk\" | \"ngk\"; effectiveAt: unknown; relativeFactor: number; constant: number; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.costs.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ productOverheadFactor?: undefined | number; workHourOverheadFactor?: undefined | number; specialRecordOverheadFactor?: undefined | number; toolOverheadFactor?: undefined | number; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.global.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ key: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.global.get",
        kind: ProcedureKind::Query,
        input_ts: "{ key: string; }",
        output_ts: "{ key: string; name: any; }",
    },
    RawContractSpec {
        path: "settings.global.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ key: string; name: any; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.language.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ locale: \"de\" | \"en\"; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.publicGlobal.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ key: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.publicGlobal.get",
        kind: ProcedureKind::Query,
        input_ts: "{ key: string; }",
        output_ts: "{ key: string; name: any; }",
    },
    RawContractSpec {
        path: "settings.publicGlobal.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ key: string; name: any; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.tenantLogo.completeUpload",
        kind: ProcedureKind::Mutation,
        input_ts: "{ generationId: string; etag?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "settings.tenantLogo.createUpload",
        kind: ProcedureKind::Mutation,
        input_ts: "{ fileName: string; mimeType: string; sizeBytes?: undefined | null | number; }",
        output_ts: "{ generationId: string; uploadUrl: string; uploadMethod: \"PUT\"; uploadHeaders: Record<string, string>; expiresAt: Date; }",
    },
    RawContractSpec {
        path: "settings.tenantLogo.get",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ status: \"none\" | \"processing\" | \"failed\" | \"queued\" | \"ready\" | \"uploading\"; mimeType: null | string; fileName: null | string; width: null | number; height: null | number; downloadUrl: null | string; downloadExpiresAt: null | Date; error: null | string; }",
    },
    RawContractSpec {
        path: "settings.tenantName.get",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ companyName: null | string; }",
    },
    RawContractSpec {
        path: "settings.tenantName.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ companyName: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.archive",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.brands",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "string[]",
    },
    RawContractSpec {
        path: "tools.categories",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "string[]",
    },
    RawContractSpec {
        path: "tools.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ customId: number; brand: string; category: string; label?: undefined | null | string; purchasePrice?: undefined | null | number; usageCostPerDay?: undefined | null | number; status?: undefined | null | \"lost\" | \"broken\"; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "tools.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; customId: number; brand: string; category: string; label: null | string; purchasePrice: null | number; usageCostPerDay: null | number; status: null | \"lost\" | \"broken\"; available: boolean; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; archivedSince: null | Date; }",
    },
    RawContractSpec {
        path: "tools.inventories.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ toolId: string; comment?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "tools.inventories.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.inventories.list",
        kind: ProcedureKind::Query,
        input_ts: "{ toolId?: undefined | null | string; }",
        output_ts: "{ id: string; toolId: string; comment: null | string; createdAt: Date; }[]",
    },
    RawContractSpec {
        path: "tools.inventories.overview",
        kind: ProcedureKind::Query,
        input_ts: "{ hadInventory: boolean; days?: undefined | number; }",
        output_ts: "{ id: string; customId: number; brand: string; category: string; label: null | string; status: null | \"lost\" | \"broken\"; available: boolean; archivedSince: null | Date; lastInventoryAt: null | Date; lastResponsibleUserId: null | string; lastResponsibleFirstName: null | string; lastResponsibleLastName: null | string; }[]",
    },
    RawContractSpec {
        path: "tools.list",
        kind: ProcedureKind::Query,
        input_ts: "{ search?: undefined | null | string; status?: undefined | null | \"lost\" | \"broken\" | \"available\" | \"unavailable\"; brand?: undefined | null | string; category?: undefined | null | string; }",
        output_ts: "{ id: string; customId: number; brand: string; category: string; label: null | string; purchasePrice: null | number; usageCostPerDay: null | number; status: null | \"lost\" | \"broken\"; available: boolean; createdByUserId: null | string; createdAt: Date; modifiedAt: Date; archivedSince: null | Date; }[]",
    },
    RawContractSpec {
        path: "tools.suggestNextCustomId",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "number",
    },
    RawContractSpec {
        path: "tools.track",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { projectId?: undefined | null | string; responsibleUserId?: undefined | null | string; deadlineAt?: unknown; comment?: undefined | null | string; }; }",
        output_ts: "{ trackingId: string; }",
    },
    RawContractSpec {
        path: "tools.trackings.list",
        kind: ProcedureKind::Query,
        input_ts: "{ finished?: undefined | null | false | true; toolId?: undefined | null | string; projectId?: undefined | null | string; responsibleUserId?: undefined | null | string; startedByUserId?: undefined | null | string; endedByUserId?: undefined | null | string; startedBefore?: unknown; startedAfter?: unknown; endedBefore?: unknown; endedAfter?: unknown; limit?: undefined | number; offset?: undefined | number; }",
        output_ts: "{ id: string; toolId: string; projectId: null | string; responsibleUserId: null | string; startedByUserId: null | string; endedByUserId: null | string; toolUsageCostPerDay: null | number; comment: null | string; startedAt: Date; endedAt: null | Date; deadlineAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "tools.trackings.transfers.accept",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; projectId?: undefined | null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.trackings.transfers.deny",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.trackings.transfers.list",
        kind: ProcedureKind::Query,
        input_ts: "{ toolId?: undefined | null | string; status?: undefined | null | \"open\" | \"denied\" | \"accepted\"; createdByUserId?: undefined | null | string; transferToUserId?: undefined | null | string; projectId?: undefined | null | string; limit?: undefined | number; offset?: undefined | number; }",
        output_ts: "{ id: string; toolTrackingId: string; toolId: string; transferToUserId: string; createdByUserId: string; projectId: null | string; status: \"open\" | \"denied\" | \"accepted\"; notes: null | string; createdAt: Date; responsibleUserId: null | string; toolUsageCostPerDay: null | number; }[]",
    },
    RawContractSpec {
        path: "tools.trackings.transfers.request",
        kind: ProcedureKind::Mutation,
        input_ts: "{ toolTrackingId: string; transferToUserId?: undefined | null | string; projectId?: undefined | null | string; notes?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "tools.unarchive",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.untrack",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "tools.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { brand?: undefined | string; category?: undefined | string; label?: undefined | null | string; purchasePrice?: undefined | null | number; usageCostPerDay?: undefined | null | number; status?: undefined | null | \"lost\" | \"broken\"; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.activate",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.archive",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ username: string; firstName: string; lastName?: undefined | null | string; email?: undefined | null | string; phone?: undefined | null | string; contractType?: undefined | \"internal\" | \"external\" | \"subcontractor\"; costPerHour?: undefined | null | number; supervisorUserId?: undefined | null | string; }",
        output_ts: "{ id: string; }",
    },
    RawContractSpec {
        path: "users.deactivate",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.get",
        kind: ProcedureKind::Query,
        input_ts: "{ id: string; }",
        output_ts: "{ id: string; salutation: null | string; firstName: string; lastName: null | string; username: string; email: null | string; phone: null | string; contractType: \"internal\" | \"external\" | \"subcontractor\"; costPerHour: null | number; supervisorUserId: null | string; createdAt: Date; modifiedAt: Date; deactivatedAt: null | Date; archivedAt: null | Date; }",
    },
    RawContractSpec {
        path: "users.list",
        kind: ProcedureKind::Query,
        input_ts: "{ search?: undefined | null | string; deactivated?: undefined | null | false | true; includeArchived?: undefined | false | true; }",
        output_ts: "{ id: string; salutation: null | string; firstName: string; lastName: null | string; username: string; email: null | string; phone: null | string; contractType: \"internal\" | \"external\" | \"subcontractor\"; costPerHour: null | number; supervisorUserId: null | string; createdAt: Date; modifiedAt: Date; deactivatedAt: null | Date; archivedAt: null | Date; }[]",
    },
    RawContractSpec {
        path: "users.roles.get",
        kind: ProcedureKind::Query,
        input_ts: "{ userId: string; }",
        output_ts: "(\":admin\" | \":llm\" | \"view:users\" | \"manage:users\" | \"delete:users\" | \"view:projects\" | \"manage:projects\" | \"delete:projects\" | \"view:projectDeployments\" | \"manage:projectDeployments\" | \"delete:projectDeployments\" | \"view:userVacations\" | \"manage:userVacations\" | \"delete:userVacations\" | \"view:tools\" | \"manage:tools\" | \"delete:tools\" | \"view:toolTrackings\" | \"manage:toolTrackings\" | \"delete:toolTrackings\" | \"view:toolInventories\" | \"manage:toolInventories\" | \"delete:toolInventories\" | \"view:products\" | \"manage:products\" | \"delete:products\" | \"view:deliveryNotes\" | \"manage:deliveryNotes\" | \"delete:deliveryNotes\" | \"view:productVendors\" | \"manage:productVendors\" | \"delete:productVendors\" | \"view:productPriceRecords\" | \"manage:productPriceRecords\" | \"delete:productPriceRecords\" | \"view:customers\" | \"manage:customers\" | \"delete:customers\" | \"view:contacts\" | \"manage:contacts\" | \"delete:contacts\" | \"view:dailyProjectReports\" | \"manage:dailyProjectReports\" | \"delete:dailyProjectReports\" | \"view:regieReports\" | \"manage:regieReports\" | \"delete:regieReports\" | \"view:clientScripts\" | \"manage:clientScripts\" | \"delete:clientScripts\")[]",
    },
    RawContractSpec {
        path: "users.roles.list",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "(\":admin\" | \":llm\" | \"view:users\" | \"manage:users\" | \"delete:users\" | \"view:projects\" | \"manage:projects\" | \"delete:projects\" | \"view:projectDeployments\" | \"manage:projectDeployments\" | \"delete:projectDeployments\" | \"view:userVacations\" | \"manage:userVacations\" | \"delete:userVacations\" | \"view:tools\" | \"manage:tools\" | \"delete:tools\" | \"view:toolTrackings\" | \"manage:toolTrackings\" | \"delete:toolTrackings\" | \"view:toolInventories\" | \"manage:toolInventories\" | \"delete:toolInventories\" | \"view:products\" | \"manage:products\" | \"delete:products\" | \"view:deliveryNotes\" | \"manage:deliveryNotes\" | \"delete:deliveryNotes\" | \"view:productVendors\" | \"manage:productVendors\" | \"delete:productVendors\" | \"view:productPriceRecords\" | \"manage:productPriceRecords\" | \"delete:productPriceRecords\" | \"view:customers\" | \"manage:customers\" | \"delete:customers\" | \"view:contacts\" | \"manage:contacts\" | \"delete:contacts\" | \"view:dailyProjectReports\" | \"manage:dailyProjectReports\" | \"delete:dailyProjectReports\" | \"view:regieReports\" | \"manage:regieReports\" | \"delete:regieReports\" | \"view:clientScripts\" | \"manage:clientScripts\" | \"delete:clientScripts\")[]",
    },
    RawContractSpec {
        path: "users.roles.set",
        kind: ProcedureKind::Mutation,
        input_ts: "{ userId: string; assignments: { \":admin\": undefined | null | false | true; \":llm\": undefined | null | false | true; \"view:users\": undefined | null | false | true; \"manage:users\": undefined | null | false | true; \"delete:users\": undefined | null | false | true; \"view:projects\": undefined | null | false | true; \"manage:projects\": undefined | null | false | true; \"delete:projects\": undefined | null | false | true; \"view:projectDeployments\": undefined | null | false | true; \"manage:projectDeployments\": undefined | null | false | true; \"delete:projectDeployments\": undefined | null | false | true; \"view:userVacations\": undefined | null | false | true; \"manage:userVacations\": undefined | null | false | true; \"delete:userVacations\": undefined | null | false | true; \"view:tools\": undefined | null | false | true; \"manage:tools\": undefined | null | false | true; \"delete:tools\": undefined | null | false | true; \"view:toolTrackings\": undefined | null | false | true; \"manage:toolTrackings\": undefined | null | false | true; \"delete:toolTrackings\": undefined | null | false | true; \"view:toolInventories\": undefined | null | false | true; \"manage:toolInventories\": undefined | null | false | true; \"delete:toolInventories\": undefined | null | false | true; \"view:products\": undefined | null | false | true; \"manage:products\": undefined | null | false | true; \"delete:products\": undefined | null | false | true; \"view:deliveryNotes\": undefined | null | false | true; \"manage:deliveryNotes\": undefined | null | false | true; \"delete:deliveryNotes\": undefined | null | false | true; \"view:productVendors\": undefined | null | false | true; \"manage:productVendors\": undefined | null | false | true; \"delete:productVendors\": undefined | null | false | true; \"view:productPriceRecords\": undefined | null | false | true; \"manage:productPriceRecords\": undefined | null | false | true; \"delete:productPriceRecords\": undefined | null | false | true; \"view:customers\": undefined | null | false | true; \"manage:customers\": undefined | null | false | true; \"delete:customers\": undefined | null | false | true; \"view:contacts\": undefined | null | false | true; \"manage:contacts\": undefined | null | false | true; \"delete:contacts\": undefined | null | false | true; \"view:dailyProjectReports\": undefined | null | false | true; \"manage:dailyProjectReports\": undefined | null | false | true; \"delete:dailyProjectReports\": undefined | null | false | true; \"view:regieReports\": undefined | null | false | true; \"manage:regieReports\": undefined | null | false | true; \"delete:regieReports\": undefined | null | false | true; \"view:clientScripts\": undefined | null | false | true; \"manage:clientScripts\": undefined | null | false | true; \"delete:clientScripts\": undefined | null | false | true; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.supervisors.getDefault",
        kind: ProcedureKind::Query,
        input_ts: "void",
        output_ts: "{ userId: null | string; }",
    },
    RawContractSpec {
        path: "users.supervisors.setDefault",
        kind: ProcedureKind::Mutation,
        input_ts: "{ userId: null | string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.unarchive",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.update",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; data: { username?: undefined | string; firstName?: undefined | string; lastName?: undefined | null | string; email?: undefined | null | string; phone?: undefined | null | string; contractType?: undefined | null | \"internal\" | \"external\" | \"subcontractor\"; costPerHour?: undefined | null | number; supervisorUserId?: undefined | null | string; }; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.vacations.approve",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.vacations.create",
        kind: ProcedureKind::Mutation,
        input_ts: "{ from: unknown; to: unknown; userId?: undefined | null | string; note?: undefined | null | string; }",
        output_ts: "{ id: string; status: \"denied\" | \"requested\" | \"approved\"; }",
    },
    RawContractSpec {
        path: "users.vacations.delete",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.vacations.deny",
        kind: ProcedureKind::Mutation,
        input_ts: "{ id: string; reason: string; }",
        output_ts: "{ success: true; }",
    },
    RawContractSpec {
        path: "users.vacations.list",
        kind: ProcedureKind::Query,
        input_ts: "{ from?: unknown; to?: unknown; userId?: undefined | null | string; includeDenied?: undefined | false | true; }",
        output_ts: "{ id: string; userId: string; from: Date; to: Date; status: \"denied\" | \"requested\" | \"approved\"; note: null | string; denialReason: null | string; requestedByUserId: null | string; decidedByUserId: null | string; decidedAt: null | Date; createdAt: Date; modifiedAt: Date; canApprove: boolean; canDeny: boolean; canDelete: boolean; }[]",
    },
];
