//! First-party tRPC-compatible batching, dispatch, and contract generation.

use std::{
    any::TypeId,
    collections::{BTreeMap, HashSet},
    future::Future,
    pin::Pin,
    sync::Arc,
};

use axum::{
    Json, Router,
    body::Bytes,
    extract::{Path, RawQuery, State},
    http::{HeaderMap, Method},
    response::{IntoResponse, Response},
    routing::any,
};
use futures_util::future::join_all;
use serde::{Serialize, de::DeserializeOwned};
use serde_json::{Value, json};
use tower_http::{compression::CompressionLayer, cors::CorsLayer, trace::TraceLayer};
use ts_rs::{Config, TS, TypeVisitor};

use crate::{
    error::{ErrorCode, RpcError, RpcResult},
    superjson,
};

type HandlerFuture = Pin<Box<dyn Future<Output = RpcResult<Value>> + Send>>;
type Handler = dyn Fn(RequestContext, Value) -> HandlerFuture + Send + Sync;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProcedureKind {
    Query,
    Mutation,
}

impl ProcedureKind {
    fn accepts(self, method: &Method) -> bool {
        matches!(
            (self, method),
            (Self::Query, &Method::GET) | (Self::Mutation, &Method::POST)
        )
    }

    fn typescript_map_name(self) -> &'static str {
        match self {
            Self::Query => "Query",
            Self::Mutation => "Mutation",
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct RawContractSpec {
    pub path: &'static str,
    pub kind: ProcedureKind,
    pub input_ts: &'static str,
    pub output_ts: &'static str,
}

#[derive(Clone)]
struct Procedure {
    kind: ProcedureKind,
    handler: Arc<Handler>,
    input_ts: String,
    output_ts: String,
}

#[derive(Debug, Clone)]
pub struct RequestContext {
    pub headers: HeaderMap,
}

#[derive(Clone, Default)]
pub struct ProcedureRegistry {
    procedures: Arc<BTreeMap<String, Procedure>>,
    declarations: Arc<BTreeMap<String, String>>,
}

impl ProcedureRegistry {
    pub fn builder() -> ProcedureRegistryBuilder {
        ProcedureRegistryBuilder::default()
    }

    pub fn typescript_contract(&self) -> String {
        let mut output = String::from("// Generated by sortsys-api. Do not edit.\n\n");
        for declaration in self.declarations.values() {
            output.push_str(&format!("export {declaration}\n\n"));
        }
        for kind in [ProcedureKind::Query, ProcedureKind::Mutation] {
            let name = kind.typescript_map_name();
            output.push_str(&format!("export type {name}Inputs = {{\n"));
            for (path, procedure) in self.procedures.iter().filter(|(_, p)| p.kind == kind) {
                output.push_str(&format!("  {:?}: {};\n", path, procedure.input_ts));
            }
            output.push_str("};\n\n");
            output.push_str(&format!("export type {name}Outputs = {{\n"));
            for (path, procedure) in self.procedures.iter().filter(|(_, p)| p.kind == kind) {
                output.push_str(&format!("  {:?}: {};\n", path, procedure.output_ts));
            }
            output.push_str("};\n\n");
        }
        output
    }

    async fn call(
        &self,
        path: String,
        method: Method,
        context: RequestContext,
        input: Value,
    ) -> Value {
        let Some(procedure) = self.procedures.get(&path) else {
            return RpcError::not_found(&path).into_wire();
        };

        if !procedure.kind.accepts(&method) {
            return RpcError::new(
                ErrorCode::MethodNotSupported,
                format!("Unsupported {method} request to procedure at path \"{path}\""),
            )
            .at_path(path)
            .into_wire();
        }

        match (procedure.handler)(context, input).await {
            Ok(output) => json!({
                "result": {
                    "data": superjson::encode(output),
                },
            }),
            Err(error) => error.at_path_if_missing(path).into_wire(),
        }
    }
}

#[derive(Default)]
pub struct ProcedureRegistryBuilder {
    procedures: BTreeMap<String, Procedure>,
    declarations: BTreeMap<String, String>,
}

impl ProcedureRegistryBuilder {
    pub fn raw_stub(mut self, spec: &RawContractSpec) -> Self {
        let path = spec.path.to_owned();
        let error_path = path.clone();
        let handler: Arc<Handler> = Arc::new(move |_context, _input| {
            let error_path = error_path.clone();
            Box::pin(async move {
                Err(RpcError::new(
                    ErrorCode::InternalServerError,
                    "contract-only procedure was called",
                )
                .at_path(error_path))
            })
        });
        let previous = self.procedures.insert(
            path.clone(),
            Procedure {
                kind: spec.kind,
                handler,
                input_ts: spec.input_ts.to_owned(),
                output_ts: spec.output_ts.to_owned(),
            },
        );
        assert!(previous.is_none(), "duplicate RPC procedure path: {path}");
        self
    }

    pub fn query_json<F, Fut>(self, path: impl Into<String>, handler: F) -> Self
    where
        F: Fn(RequestContext, Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = RpcResult<Value>> + Send + 'static,
    {
        self.register_json(ProcedureKind::Query, path, handler)
    }

    pub fn mutation_json<F, Fut>(self, path: impl Into<String>, handler: F) -> Self
    where
        F: Fn(RequestContext, Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = RpcResult<Value>> + Send + 'static,
    {
        self.register_json(ProcedureKind::Mutation, path, handler)
    }

    fn register_json<F, Fut>(
        mut self,
        kind: ProcedureKind,
        path: impl Into<String>,
        handler: F,
    ) -> Self
    where
        F: Fn(RequestContext, Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = RpcResult<Value>> + Send + 'static,
    {
        let path = path.into();
        let handler = Arc::new(handler);
        let erased: Arc<Handler> = Arc::new(move |context, input| {
            let handler = Arc::clone(&handler);
            Box::pin(async move { handler(context, input).await })
        });
        let previous = self.procedures.insert(
            path.clone(),
            Procedure {
                kind,
                handler: erased,
                input_ts: "unknown".to_owned(),
                output_ts: "unknown".to_owned(),
            },
        );
        assert!(previous.is_none(), "duplicate RPC procedure path: {path}");
        self
    }

    pub fn query<I, O, F, Fut>(self, path: impl Into<String>, handler: F) -> Self
    where
        I: DeserializeOwned + TS + Send + 'static,
        O: Serialize + TS + Send + 'static,
        F: Fn(RequestContext, I) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = RpcResult<O>> + Send + 'static,
    {
        self.register(ProcedureKind::Query, path, handler)
    }

    pub fn mutation<I, O, F, Fut>(self, path: impl Into<String>, handler: F) -> Self
    where
        I: DeserializeOwned + TS + Send + 'static,
        O: Serialize + TS + Send + 'static,
        F: Fn(RequestContext, I) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = RpcResult<O>> + Send + 'static,
    {
        self.register(ProcedureKind::Mutation, path, handler)
    }

    pub fn query_stub<I, O>(self, path: impl Into<String>) -> Self
    where
        I: DeserializeOwned + TS + Send + 'static,
        O: Serialize + TS + Send + 'static,
    {
        self.query(path, |_context, _input: I| async move {
            Err(RpcError::new(
                ErrorCode::InternalServerError,
                "contract-only procedure was called",
            )) as RpcResult<O>
        })
    }

    pub fn mutation_stub<I, O>(self, path: impl Into<String>) -> Self
    where
        I: DeserializeOwned + TS + Send + 'static,
        O: Serialize + TS + Send + 'static,
    {
        self.mutation(path, |_context, _input: I| async move {
            Err(RpcError::new(
                ErrorCode::InternalServerError,
                "contract-only procedure was called",
            )) as RpcResult<O>
        })
    }

    fn register<I, O, F, Fut>(
        mut self,
        kind: ProcedureKind,
        path: impl Into<String>,
        handler: F,
    ) -> Self
    where
        I: DeserializeOwned + TS + Send + 'static,
        O: Serialize + TS + Send + 'static,
        F: Fn(RequestContext, I) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = RpcResult<O>> + Send + 'static,
    {
        let path = path.into();
        let error_path = path.clone();
        let handler = Arc::new(handler);
        let erased: Arc<Handler> = Arc::new(move |context, input| {
            let handler = Arc::clone(&handler);
            let error_path = error_path.clone();
            Box::pin(async move {
                let input = serde_json::from_value::<I>(input)
                    .map_err(|error| RpcError::bad_input(&error_path, error.to_string()))?;
                let output = handler(context, input).await?;
                serde_json::to_value(output)
                    .map_err(|error| RpcError::internal(&error_path, error.to_string()))
            })
        });

        let previous = self.procedures.insert(
            path.clone(),
            Procedure {
                kind,
                handler: erased,
                input_ts: if TypeId::of::<I>() == TypeId::of::<()>() {
                    "void".to_owned()
                } else {
                    let rendered = I::inline(&Config::default());
                    if I::IS_OPTION {
                        format!(
                            "{} | void",
                            rendered.strip_suffix(" | null").unwrap_or(&rendered)
                        )
                    } else {
                        rendered
                    }
                },
                output_ts: O::inline(&Config::default()),
            },
        );
        assert!(previous.is_none(), "duplicate RPC procedure path: {path}");
        collect_dependencies::<I>(&mut self.declarations);
        collect_dependencies::<O>(&mut self.declarations);
        self
    }

    pub fn build(self) -> ProcedureRegistry {
        ProcedureRegistry {
            procedures: Arc::new(self.procedures),
            declarations: Arc::new(self.declarations),
        }
    }
}

fn collect_dependencies<T: TS + 'static>(declarations: &mut BTreeMap<String, String>) {
    struct Collector<'a> {
        config: Config,
        declarations: &'a mut BTreeMap<String, String>,
        visited: HashSet<TypeId>,
    }

    impl TypeVisitor for Collector<'_> {
        fn visit<T: TS + 'static + ?Sized>(&mut self) {
            let type_id = TypeId::of::<T>();
            if !self.visited.insert(type_id) || T::output_path().is_none() {
                return;
            }
            self.declarations
                .entry(T::ident(&self.config))
                .or_insert_with(|| T::decl(&self.config));
            T::visit_dependencies(self);
        }
    }

    let mut collector = Collector {
        config: Config::default(),
        declarations,
        visited: HashSet::new(),
    };
    T::visit_dependencies(&mut collector);
}

pub fn http_router(registry: ProcedureRegistry) -> Router {
    Router::new()
        .route("/{*path}", any(handle_http))
        .with_state(registry)
        .layer(CompressionLayer::new())
        .layer(CorsLayer::permissive())
        .layer(TraceLayer::new_for_http())
}

async fn handle_http(
    State(registry): State<ProcedureRegistry>,
    Path(path): Path<String>,
    RawQuery(raw_query): RawQuery,
    method: Method,
    headers: HeaderMap,
    body: Bytes,
) -> Response {
    let is_batch = raw_query
        .as_deref()
        .and_then(|query| query_parameter(query, "batch"))
        .is_some_and(|value| value == "1");
    let serialized_input = if method == Method::GET {
        raw_query
            .as_deref()
            .and_then(|query| query_parameter(query, "input"))
            .unwrap_or_else(|| "{}".to_owned())
    } else {
        String::from_utf8_lossy(&body).into_owned()
    };

    let input: Value = match serde_json::from_str(&serialized_input) {
        Ok(input) => input,
        Err(error) => {
            let response = RpcError::new(ErrorCode::ParseError, error.to_string()).into_wire();
            return Json(if is_batch {
                json!([response])
            } else {
                response
            })
            .into_response();
        }
    };

    let paths: Vec<String> = path.split(',').map(str::to_owned).collect();
    let calls = paths.into_iter().enumerate().map(|(index, path)| {
        let registry = registry.clone();
        let context = RequestContext {
            headers: headers.clone(),
        };
        let method = method.clone();
        let envelope = if is_batch {
            input
                .get(index.to_string())
                .cloned()
                .unwrap_or_else(|| json!({ "json": null }))
        } else {
            input.clone()
        };
        let input = superjson::decode(envelope);
        async move { registry.call(path, method, context, input).await }
    });

    let responses = join_all(calls).await;
    let response = if is_batch {
        Value::Array(responses)
    } else {
        responses.into_iter().next().unwrap_or_else(|| {
            RpcError::new(ErrorCode::BadRequest, "RPC request has no procedure path").into_wire()
        })
    };
    Json(response).into_response()
}

fn query_parameter(query: &str, name: &str) -> Option<String> {
    url::form_urlencoded::parse(query.as_bytes())
        .find_map(|(key, value)| (key == name).then(|| value.into_owned()))
}

#[cfg(test)]
mod tests {
    use axum::{
        body::Body,
        http::{Request, StatusCode},
    };
    use http_body_util::BodyExt;
    use serde_json::{Value, json};
    use tower::ServiceExt;

    use crate::{app, registry};

    #[tokio::test]
    async fn batched_ping_matches_the_current_wire_contract() {
        let input = "%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%2C%22v%22%3A1%7D%7D%2C%221%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%2C%22v%22%3A1%7D%7D%7D";
        let response = app()
            .oneshot(
                Request::builder()
                    .uri(format!("/ping,ping?batch=1&input={input}"))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let body: Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(
            body,
            json!([
                { "result": { "data": { "json": "pong" } } },
                { "result": { "data": { "json": "pong" } } },
            ]),
        );
    }

    #[tokio::test]
    async fn missing_mutation_matches_the_current_error_contract() {
        let response = app()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/missing?batch=1")
                    .header("content-type", "application/json")
                    .body(Body::from(r#"{"0":{"json":{"x":1}}}"#))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let body: Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(body[0]["error"]["json"]["code"], json!(-32004));
        assert_eq!(body[0]["error"]["json"]["data"]["code"], json!("NOT_FOUND"));
        assert_eq!(body[0]["error"]["json"]["data"]["path"], json!("missing"));
        assert_eq!(
            body[0]["error"]["meta"]["values"]["data.validationErrors"],
            json!(["undefined"]),
        );
    }

    #[test]
    fn generated_contract_contains_registered_procedures() {
        let contract = registry().typescript_contract();
        assert!(contract.contains("\"ping\": void;"));
        assert!(contract.contains("\"ping\": string;"));
    }
}
