export type EnglishDocContent = {
  title: string;
  lead: string;
  category: string;
  paragraphs: string[];
  faqs: Array<{ question: string; answer: string[] }>;
  scriptExamples?: Array<{ title: string; description: string }>;
  keywords: string[];
};

const faq = (question: string, answer: string) => ({ question, answer: [answer] });

export const ENGLISH_DOCS: Record<string, EnglishDocContent> = {
  'client-skripte': {
    title: 'Client scripts',
    lead: 'Client scripts automate browser workflows while running in an isolated sandbox.',
    category: 'Automation',
    paragraphs: [
      'Create client scripts under Administration > Scripts. Name the script first, then edit and save its JavaScript in the editor.',
      `Scripts are JavaScript modules and may use top-level await. Static imports and exports are blocked; use dynamic imports such as <code>await import('sortsys-client')</code>.`,
      `Five modules are available: <code>sortsys-client</code>, <code>sortsys-popups</code>, <code>sortsys-modal-forms</code>, <code>sortsys-log</code>, and <code>sortsys-utils</code>. Other imports are rejected.`,
      `<code>console</code> is unavailable. Use <code>const { log } = await import('sortsys-log')</code> instead.`,
      `Code runs in a worker without <code>window</code>, <code>document</code>, storage, <code>fetch</code>, <code>alert</code>, or <code>prompt</code>.`,
      'Dialog HTML is sanitized before display. Scripts, iframes, event handlers, and unsafe links are removed.',
      `Both <code>client.query</code> and <code>client.mutate</code> return <code>[data, error]</code>. Check and throw errors explicitly.`,
      'The examples below can be edited and run directly. Changes made there are not saved.',
    ],
    scriptExamples: [
      { title: 'Show a confirmation', description: `Uses <code>sortsys-popups</code>. Dialog HTML is sanitized before display.` },
      { title: 'Read API data', description: `Uses <code>sortsys-client</code>. Every query returns <code>[data, error]</code>.` },
      { title: 'Open a modal form', description: `Uses <code>sortsys-modal-forms</code> with validation and filtered options.` },
      { title: 'Use utilities', description: `Uses <code>sortsys-utils</code> for encoding, escaping, and basic statistics.` },
      { title: 'Inspect the sandbox', description: 'Shows that page and browser globals are unavailable.' },
    ],
    faqs: [
      faq('Why do regular imports fail?', 'Only dynamic imports of approved modules are accepted so scripts cannot load arbitrary code.'),
      faq('Can a script access the page directly?', 'No. It communicates only through the approved bridge modules.'),
      faq('When should I use requireDangerConfirmation?', 'Use it for changes, deletions, and other actions that are difficult to undo.'),
    ],
    keywords: ['client scripts', 'automation', 'sandbox', 'imports', 'API', 'worker'],
  },
  projekt: {
    title: 'Project',
    lead: 'A project represents a contract or construction site to which operational records are assigned.',
    category: 'Master data',
    paragraphs: [
      'A project is the central record for a contract or construction site, its work, evidence, and analysis.',
      'A distinct title is enough to start. The order date, customer, site address, project manager, and contacts can be added later.',
      'Customer, address, users, planning, files, reports, delivery notes, tool bookings, and costs remain accessible through the project.',
      'The project address is the place of work and may differ from the customer address.',
      'Contacts can have project-specific roles such as Owner, Architect, or Site manager without duplicating their details.',
      'Project assignments support resource planning, restricted visibility, and clear responsibility.',
      'Daily reports record normal progress; time-and-material reports record additional work; delivery notes and tool bookings record resources.',
      'Store site photos, documents, and supported drawings in the project files.',
      'The cost overview combines recorded materials, labour, tools, special items, quotations, invoices, and overhead.',
      'All costs and quotation or invoice totals are net amounts. Missing prices or rates leave the overview incomplete.',
      'Completed projects remain available with their reports, files, and costs.',
      'Use a title that clearly identifies the contract, place, or construction site.',
    ],
    faqs: [
      faq('When should I create a project?', 'Create one when work needs separate tracking by contract, site, or cost centre.'),
      faq('What happens on completion?', 'The project leaves active lists but remains searchable with its records.'),
      faq('Why are costs incomplete?', 'Check missing prices, hourly rates, daily tool rates, and project assignments.'),
    ],
    keywords: ['project', 'construction site', 'customer', 'costs', 'reports', 'files'],
  },
  bautagesbericht: {
    title: 'Daily construction report',
    lead: 'A daily construction report records work completed on a project on a specific day.',
    category: 'Construction site',
    paragraphs: [
      'A report describes one calendar day and contains completed work, weather, and working hours.',
      'Attach photos that document that day; store general documents in the project files.',
      'Assigning the project adds the report to the project record and includes its hours in exports and cost calculations.',
      'Use one distinct report per project and calendar day.',
      'Correct the existing report instead of creating a duplicate for the same day.',
      'Regular hours belong here; separately approved additional work belongs in a time-and-material report.',
      'Each time entry names a user and hours, which enter costs using the applicable rate.',
      'Describe work precisely enough for the office, site manager, or customer to understand later.',
      'Keep weather and photos relevant to the documented day.',
      'The weekly form is an input aid; saved records remain individual daily reports.',
    ],
    faqs: [
      faq('When is a daily report sufficient?', 'Use it for normal daily documentation that needs no separate approval.'),
      faq('What is the weekly report?', 'It is one form that creates individual reports for several calendar days.'),
      faq('Can I report a future day?', 'No. Reports record work that actually happened.'),
    ],
    keywords: ['daily report', 'weather', 'working hours', 'photos', 'week'],
  },
  regiebericht: {
    title: 'Time-and-material report',
    lead: 'A time-and-material report records additional work billed by time and materials.',
    category: 'Construction site',
    paragraphs: [
      'The report records additional work with its project, date, description, hours, materials, and special items.',
      'It covers a calendar week; choose any day in that week and assign hours from Monday through Sunday.',
      'The project connects the work to the correct contract, site, and customer.',
      'Unlike a daily report, it documents separately verifiable additional work.',
      'Do not record the same hours in both reports because that duplicates evidence and costs.',
      'State the work, reason, and scope in a short, concrete description.',
      'Use catalogue products for consistent names or free-form items for exceptional materials.',
      'Product items record quantity and unit; free-form items also carry their own name.',
      'Reports stay in the project record and can be opened and exported separately.',
      'Check the week, users, hours, and quantities before export.',
    ],
    faqs: [
      faq('When is this report unnecessary?', 'A daily report is enough when work needs no separate approval or billing.'),
      faq('Which week date should I select?', 'Choose any day in the relevant Monday-to-Sunday week.'),
      faq('Why are item costs missing?', 'A valid purchase price may be missing for a product item.'),
    ],
    keywords: ['time and material', 'additional work', 'week', 'hours', 'material'],
  },
  lieferschein: {
    title: 'Delivery note',
    lead: 'A delivery note assigns materials and quantities to a project.',
    category: 'Materials',
    paragraphs: [
      'A delivery note records project, document number, date, products, quantities, comments, and free-form items.',
      'The document date determines which prices apply. Use the comment for supplier details, storage information, or discrepancies.',
      'Always assign the correct project so records and costs reflect the right site.',
      'Catalogue products provide consistent names and prices; free-form items suit one-off materials.',
      'Product units convert to the base unit using the configured factor.',
      'Use the external delivery note number for search and invoice checks.',
      'Keep internal notes in the comment rather than changing the document number.',
      'A delivery note records a material movement, not an invoice.',
      'Products use applicable purchase prices; free-form items carry a net price. Missing prices leave costs open.',
      'Correct project assignment prevents distorted costs and failed searches.',
    ],
    faqs: [
      faq('Can I omit the project?', 'No. Materials need a project for evidence, search, and costs.'),
      faq('When should I use a free-form item?', 'Use one for a one-off material that should not become a catalogue product.'),
      faq('Why does an item have no costs?', 'No applicable purchase price was found for the document date.'),
    ],
    keywords: ['delivery note', 'materials', 'quantity', 'supplier', 'price'],
  },
  werkzeugbuchung: {
    title: 'Tool booking',
    lead: 'A tool booking records where a tool is and who is responsible for it.',
    category: 'Tools',
    paragraphs: [
      'Each issue, return, or transfer records the tool, responsible user, project, and applicable period.',
      'Tool status describes condition, not the current user or project.',
      'The project shows where a tool is used and supports responsibility and cost analysis.',
      'Active bookings show current responsibility; completed bookings form the history.',
      'An inventory records an inspection but does not return or transfer a tool.',
      'Update the booking when the tool changes project.',
      'Transfer requests provide a controlled handover between responsible users.',
      'The current booking remains active until a requested transfer is processed.',
      'Bookings can enter project costs when the rate, project, and period are correct.',
      'The daily usage rate and purchase price are separate net amounts.',
    ],
    faqs: [
      faq('Who is responsible?', 'The user named in the active booking.'),
      faq('Does an inventory change the booking?', 'No. Use a return, booking, or transfer to change responsibility.'),
      faq('How do status and booking differ?', 'Status describes condition; the booking records user, project, and period.'),
    ],
    keywords: ['tool', 'booking', 'issue', 'return', 'transfer', 'inventory'],
  },
  einsatzplanung: {
    title: 'Resource planning',
    lead: 'Resource planning assigns users to projects for defined periods.',
    category: 'Planning',
    paragraphs: [
      'Planning shows intended availability and project assignments, not actual working time.',
      'Views can cover a day or week and group the same data by project or user.',
      'Each entry connects a user, period, and project.',
      'Assignments may span several days and include a comment.',
      'They support weekly planning, capacity checks, and team coordination.',
      'Leave appears alongside project planning to expose conflicts.',
      'Project interruptions also mark overlapping assignments as conflicts.',
      'Plans show intention; daily and time-and-material reports show what happened.',
      'Warnings do not alter records automatically; the planner decides what to change.',
      'Review open assignments when a project is completed.',
      'Export the visible day or week as a PDF for meetings or distribution.',
    ],
    faqs: [
      faq('Is planning working time?', 'No. Actual hours are recorded in daily or time-and-material reports.'),
      faq('What does a warning mean?', 'Leave or a project interruption overlaps the assignment.'),
      faq('What is a project interruption?', 'It blocks a project period and marks affected assignments as conflicts.'),
    ],
    keywords: ['resource planning', 'assignment', 'capacity', 'conflict', 'leave'],
  },
  urlaub: {
    title: 'Leave',
    lead: 'Leave records a user’s planned absence.',
    category: 'Personnel',
    paragraphs: [
      'Leave entries contain a period, status, and optional note.',
      'The start and end dates are inclusive. Use the same date for a single day of leave.',
      'Approved absence affects resource planning.',
      'Requested leave also appears in planning but remains marked as pending.',
      'Absence is not a project record, but it reduces available capacity.',
      'Requests stay with the user and do not trigger automatic reassignment.',
      'Supervisors or users with the required permission make the decision.',
      'Notes should contain only information needed for the decision or cover arrangements.',
    ],
    faqs: [
      faq('How do requested and approved leave differ?', 'Requested leave awaits a decision; approved leave is confirmed.'),
      faq('Why does a request appear in planning?', 'Planners need to see possible capacity shortages early.'),
      faq('Who can decide?', 'Supervisors and users with the relevant leave permission.'),
    ],
    keywords: ['leave', 'absence', 'request', 'approval', 'planning'],
  },
  produkt: {
    title: 'Product',
    lead: 'A product is a material master record used in documents and reports.',
    category: 'Master data',
    paragraphs: [
      'Products keep material names consistent in delivery notes and time-and-material reports.',
      'Manufacturer, categories, description, and a stable number improve searches.',
      'A product has a base unit and may have additional units.',
      'Each additional unit converts to the base unit using a fixed factor.',
      'Separate price records preserve changes over time.',
      'Each price has an effective date and may reference a vendor.',
      'Project context begins when a product is used in a project document.',
      'Consistent products improve cross-project cost analysis.',
      'Purchase and free-form prices are net amounts; missing prices leave costs incomplete.',
    ],
    faqs: [
      faq('When should I create a product?', 'Create one for materials that are used often enough to require consistent naming and pricing.'),
      faq('Should I overwrite an old price?', 'No. Add a new price with the correct effective date.'),
      faq('What is the base unit?', 'It is the unit used internally for comparisons and costs.'),
    ],
    keywords: ['product', 'material', 'manufacturer', 'vendor', 'price', 'unit'],
  },
  kunde: {
    title: 'Customer',
    lead: 'A customer is an organisation or person for whom projects are created.',
    category: 'Master data',
    paragraphs: [
      'Customers group projects by client for lists, communication, and analysis.',
      'Label phone numbers and email addresses so their purpose remains clear.',
      'Customer data contains name, salutation, and address.',
      'The customer address can open in a map; use the project address for the construction site.',
      'The customer is the client, while the project is a specific contract or site.',
      'Several projects can belong to one customer.',
      'Reuse an existing customer instead of creating duplicates for new projects.',
      'Maintain named contacts separately and link them where needed.',
      'Store general phone numbers on the customer and personal details on contacts.',
    ],
    faqs: [
      faq('When do customer and project addresses differ?', 'This is common for head offices and customers with several sites.'),
      faq('When should I reuse a customer?', 'Reuse it whenever the client master data already exists.'),
      faq('When should I add a contact?', 'Add one for a named person with individual contact details.'),
    ],
    keywords: ['customer', 'client', 'address', 'project', 'contact'],
  },
  kontakt: {
    title: 'Contact',
    lead: 'A contact is a named person you may need to reach.',
    category: 'Master data',
    paragraphs: [
      'Contacts store named people and can link to customers or projects.',
      'A contact can have an address and several labelled phone numbers or email addresses, such as mobile, office, or reception.',
      'A contact is not a user account and cannot sign in.',
      'Create a user account when an internal person needs sortsys access.',
      'Project contacts belong to a specific site or contract; customer contacts belong to the client in general.',
      'Link the same contact to several customers or projects. A separate project role can describe their function on each project.',
      'A contact may have several phone numbers or email addresses.',
      'Shared contact data reduces conflicting information between office and site teams.',
      'The contact page shows every linked customer and project.',
    ],
    faqs: [
      faq('Can a contact sign in?', 'No. Contacts have no credentials or permissions.'),
      faq('Do I need to create the same person more than once?', 'No. Create the contact once, then link it to every relevant customer and project.'),
      faq('What is a project role?', 'It describes the person’s function in that specific project.'),
    ],
    keywords: ['contact', 'phone', 'email', 'customer', 'project', 'role'],
  },
  rollen: {
    title: 'Roles & permissions',
    lead: 'Roles control which areas a user may view, edit, or delete.',
    category: 'Administration',
    paragraphs: [
      'Role templates set common permission combinations for jobs such as site management, warehouse, or office work.',
      'Treat a template as a starting point and adjust individual permissions where needed.',
      'Permissions combine an area with Read, Edit, or Delete. Edit includes Read; Delete is separate.',
      'A permission applies only to its named area.',
      'Project permissions control general visibility and editing.',
      'Planning, reports, and other project activity have separate permission areas.',
      'Seeing a project does not automatically grant access to all related records.',
      'Assign Read, Edit, and Delete deliberately for each area.',
      'Administrators have every permission and should be assigned carefully.',
      'A suitable template with a few additions is usually enough for daily work.',
    ],
    faqs: [
      faq('Why are there templates and individual permissions?', 'Templates cover common jobs; individual permissions handle exceptions in your organisation.'),
      faq('Is project visibility enough?', 'No. Reports, materials, tools, and administration can require additional permissions.'),
      faq('Does Edit include Delete?', 'No. Edit includes Read, while Delete remains separate.'),
    ],
    keywords: ['roles', 'permissions', 'read', 'edit', 'delete', 'administrator'],
  },
  tastaturkuerzel: {
    title: 'Keyboard shortcuts',
    lead: 'Keyboard shortcuts open common actions without a mouse.',
    category: 'Using sortsys',
    paragraphs: [
      'Shortcuts work only in the right context and are disabled in input fields.',
      'Available actions depend on the current page.',
      '<kbd>Ctrl</kbd>+<kbd>E</kbd> opens editing on supported detail pages.',
      '<kbd>Ctrl</kbd>+<kbd>P</kbd> exports the current page as PDF when available.',
      'Cost and inventory pages export their corresponding report.',
      '<kbd>Ctrl</kbd>+<kbd>N</kbd> opens creation on supported list and planning pages.',
      '<kbd>Ctrl</kbd>+<kbd>K</kbd> opens global search.',
      '<kbd>Ctrl</kbd>+<kbd>S</kbd> saves the current code in the script editor.',
    ],
    faqs: [
      faq('Why does nothing happen?', 'Check permissions, page type, input focus, and whether an export is already running.'),
      faq('What does Ctrl mean?', 'It is the control key, often labelled Strg on German keyboards.'),
      faq('Where does Ctrl+S work?', 'It saves code in the script editor, not general forms.'),
    ],
    keywords: ['keyboard', 'shortcuts', 'Ctrl', 'edit', 'PDF', 'search', 'save'],
  },
};

export const ENGLISH_DOC_SECTION_HEADINGS: Record<string, string> = {
  'Einordnung': 'Purpose',
  'Aufbau eines Skripts': 'Script structure',
  'Sicherheit und Grenzen': 'Security and limits',
  'Daten lesen und Fehler behandeln': 'Reading data and handling errors',
  'Beispiele verwenden': 'Using the examples',
  'Was zur Projektakte gehört': 'What belongs to the project record',
  'Nachweise und Kosten': 'Evidence and costs',
  'Abschluss und Benennung': 'Completion and naming',
  'Zweck': 'Purpose',
  'Regeln für die Erfassung': 'Recording rules',
  'Gute Beschreibung': 'Writing a useful description',
  'Inhalt': 'Contents',
  'Ablage im Projekt': 'Storage in the project',
  'Materialpositionen': 'Material items',
  'Prüfung und Zuordnung': 'Review and assignment',
  'Übergaben und Historie': 'Transfers and history',
  'Projektkosten': 'Project costs',
  'Planung im Projektalltag': 'Day-to-day planning',
  'Planung und Ist-Dokumentation': 'Plans and actual records',
  'Antrag und Entscheidung': 'Request and decision',
  'Auswirkung auf Planung': 'Effect on planning',
  'Preise und Einheiten': 'Prices and units',
  'Projektbezug und Kosten': 'Project context and costs',
  'Abgrenzung zum Projekt': 'Difference from projects',
  'Ansprechpartner': 'Contacts',
  'Abgrenzung zum Benutzerkonto': 'Difference from user accounts',
  'Zuordnung und Kommunikation': 'Assignments and communication',
  'Grundprinzip': 'How it works',
  'Projektrechte und Bereichsrechte': 'Project and area permissions',
  'Administratoren': 'Administrators',
  'Verfügbare Kürzel': 'Available shortcuts',
  'Überblick': 'Overview',
};
