// English translations for German canonical UI text.

export const EN_UI_TEXT: Readonly<Record<string, string>> = {
  ":admin": ":admin",
  ":admin entfernen": "Remove :admin",
  ":admin vergeben": "Grant :admin",
  ". So kannst du Änderungen transparent zu einem bestimmten Datum wirksam machen.": ". This makes changes effective transparently from a specific date.",
  "· Login:": "· Login:",
  "· Projekt": "· Project",
  "← Zurück": "← Back",
  "Abbrechen": "Cancel",
  "Abgelehnt": "Rejected",
  "abgeschlossen": "completed",
  "Abgeschlossen": "Completed",
  "Abgeschlossen am": "Completed on",
  "Abhanden": "Missing",
  "Ablehnen": "Reject",
  "Ablehnungsgrund": "Reason for rejection",
  "Ablehnungsgrund fehlt.": "A reason for rejection is required.",
  "Abmelden": "Log out",
  "Abschließen": "Complete",
  "Abschlussjahr": "Completion year",
  "Access Key ID": "Access Key ID",
  "Admin-Benutzer": "Admin user",
  "Admin-Benutzer erstellen": "Create admin user",
  "Admin-Datenbank": "Admin database",
  "Admin-Passwort": "Admin password",
  "Admin-Passwort zurücksetzen": "Reset admin password",
  "Admin-Username": "Admin username",
  "Admin-Zugriff": "Admin access",
  "Administrator": "Administrator",
  "Administrator: alle Rechte, inklusive Rollen und Organisation": "Administrator: all permissions, including roles and organization",
  "Aktion": "Action",
  "Aktion wird ausgeführt...": "Action in progress...",
  "Aktionen": "Actions",
  "Aktiv": "Active",
  "Aktivieren": "Enable",
  "Aktivität konnte nicht geladen werden:": "Activity could not be loaded:",
  "Aktueller Preis": "Current price",
  "Alle": "All",
  "Alle aufklappen": "Expand all",
  "Alle auswählen": "Select all",
  "Alle Bereiche sehen, nichts verändern.": "View every area without making changes.",
  "Alle mit diesem Bautagesbericht in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this daily report will also be deleted.",
  "Alle mit diesem Benutzer in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this user will also be deleted.",
  "Alle mit diesem Händler in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this vendor will also be deleted.",
  "Alle mit diesem Kontakt in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this contact will also be deleted.",
  "Alle mit diesem Kunden in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this customer will also be deleted.",
  "Alle mit diesem Lieferschein in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this delivery note will also be deleted.",
  "Alle mit diesem Produkt in Verbindung stehenden Daten werden damit ebenfalls gelöscht. Dies betrifft insbesondere auch Kostenschätzungen.": "All data associated with this product will also be deleted, including cost estimates.",
  "Alle mit diesem Projekt in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this project will also be deleted.",
  "Alle mit diesem Regiebericht in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this time-and-material report will also be deleted.",
  "Alle mit diesem Werkzeug in Verbindung stehenden Daten werden damit ebenfalls gelöscht.": "All data associated with this tool will also be deleted.",
  "Alle Rechte entfernen": "Remove all permissions",
  "Alle Rechte inklusive Organisation, Rollen und gefährlicher Aktionen.": "All permissions, including organization, roles, and destructive actions.",
  "Anbieter": "Provider",
  "Andere Einheiten": "Other units",
  "Änderungen": "Changes",
  "Änderungen am Titel wirken sich direkt auf Suche, Listen und Exporte aus.": "Title changes immediately affect search results, lists, and exports.",
  "Änderungen speichern": "Save changes",
  "Änderungen vor dem Speichern": "Changes before saving",
  "Anfrage stellen": "Submit request",
  "Anfragen": "Requests",
  "Anfragen,": "requests,",
  "Angebotssumme": "Offer total",
  "Angebotssumme (EUR)": "Offer total (EUR)",
  "Angebotssummen": "Offer totals",
  "Angefragt am": "Requested on",
  "Anhänge": "Attachments",
  "Anhänge konnten nicht geladen werden:": "Attachments could not be loaded:",
  "Anhänge sind für dieses Mandanten-Setup nicht aktiviert.": "Attachments are not enabled for this tenant.",
  "anlegen und ändern. Lesen ist enthalten.": "create and edit. Read access is included.",
  "Anmelden": "Sign in",
  "Anmeldename": "Username",
  "Anrede": "Salutation",
  "Anschrift": "Address",
  "Anschrift hinterlegen": "Add address",
  "Ansicht:": "View:",
  "Ansprechpartner": "Contact person",
  "Ansprechpartner entfernen": "Remove contact person",
  "Anthropic": "Anthropic",
  "Anwenden": "Apply",
  "Anwesenheit je Mitarbeiter und Tag": "Attendance by employee and day",
  "Anzahl": "Quantity",
  "API-Schlüssel": "API key",
  "Arbeitszeit": "Work hours",
  "Arbeitszeit entfernen": "Remove work-hours entry",
  "Arbeitszeit je Mitarbeiter und Tag": "Work hours by employee and day",
  "archiviert": "archived",
  "Archiviert": "Archived",
  "Archiviert am": "Archived on",
  "Archvieren": "Archive",
  "Art": "Type",
  "Artikel nicht gefunden": "Article not found",
  "Artikel suchen": "Search articles",
  "Auftrag erhalten am": "Order received on",
  "Aus Archiv holen": "Restore from archive",
  "Aus Bericht entfernen": "Remove from report",
  "Ausführbare Beispiele": "Runnable examples",
  "Ausführen": "Run",
  "Ausgabe": "Output",
  "ausgewählte Datei(en)": "selected file(s)",
  "Auswahl aufheben": "Clear selection",
  "Auswahl löschen": "Delete selection",
  "Auswahl ZIP": "Download selection as ZIP",
  "Backup": "Backup",
  "Backup hochladen": "Upload backup",
  "Backup jetzt": "Back up now",
  "Backup konnte nicht erstellt werden": "Backup could not be created",
  "Backup-Upload fehlgeschlagen": "Backup upload failed",
  "Backup-Ziel (S3)": "Backup target (S3)",
  "Backups aktivieren": "Enable backups",
  "Backups konnten nicht geladen werden:": "Backups could not be loaded:",
  "Basis-URL (optional)": "Base URL (optional)",
  "Basiseinheit": "Base unit",
  "Basiseinheit (kleinste)": "Base unit (smallest)",
  "Basismenge": "Base quantity",
  "Bauherr": "Client",
  "Bauleiter": "Site manager",
  "Bauleitung": "Site management",
  "Bautagesbericht": "Daily construction report",
  "Bautagesbericht bearbeiten": "Edit daily construction report",
  "Bautagesbericht erstellen": "Create daily construction report",
  "Bautagesbericht löschen": "Delete daily construction report",
  "Bautagesberichte": "Daily construction reports",
  "Bauwochenbericht": "Weekly construction report",
  "Bauwochenbericht erstellen": "Create weekly construction report",
  "Bauwochenberichte als Excel exportieren": "Export weekly construction reports as Excel",
  "Bauwochenberichte als PDF exportieren": "Export weekly construction reports as PDF",
  "Bauwochenberichte Excel (alle)": "Weekly construction reports: Excel (all)",
  "Bauwochenberichte PDF (alle)": "Weekly construction reports: PDF (all)",
  "Beantragen": "Request",
  "Bearbeiten": "Edit",
  "Befehl oder Suche": "Command or search",
  "Befehlspalette": "Command palette",
  "Beispiel: m, kg oder Stk. Alle weiteren Einheiten werden darauf umgerechnet.": "Example: m, kg, or pcs. All other units are converted to this unit.",
  "Benutzer": "Users",
  "Benutzer auf Projekte und Zeiträume planen.": "Schedule users for projects and periods.",
  "Benutzer bearbeiten": "Edit user",
  "Benutzer deaktivieren": "Disable user",
  "Benutzer erstellen": "Create user",
  "Benutzer ist seit dem": "User has been",
  "Benutzer konnten nicht geladen werden:": "Users could not be loaded:",
  "Benutzer löschen": "Delete user",
  "Benutzer muss ausgewählt sein.": "Select a user.",
  "Benutzer und Projekt müssen ausgewählt sein.": "Select a user and project.",
  "Benutzer werden geladen...": "Loading users...",
  "Benutzer, Vorgesetzte, Einsatzplanung und Urlaub verwalten.": "Manage users, supervisors, resource planning, and leave.",
  "Benutzerkonten, Stammdaten, Passwörter und Vorgesetzte.": "User accounts, master data, passwords, and supervisors.",
  "Beschreibe die ausgeführten Arbeiten für die gesamte Kalenderwoche.": "Describe the work completed during the entire calendar week.",
  "Beschreibung": "Description",
  "Beschreibung der Arbeiten": "Work description",
  "Betrag": "Amount",
  "Betrag als Nettowert in EUR eintragen, z.B. laut Angebot oder Rechnung.": "Enter the net amount in EUR, for example from the offer or invoice.",
  "Bezeichnung": "Name",
  "Bezeichung": "Name",
  "Bild": "Image",
  "Bilder": "Images",
  "Bis": "To",
  "Bis (Datum)": "To (date)",
  "Bis (Uhrzeit)": "To (time)",
  "Bitte einen Host auswählen": "Select a host",
  "Bitte mindestens einen Tag auswählen": "Select at least one day",
  "Bitte mindestens einen Tag auswählen.": "Select at least one day.",
  "Bitte mindestens einen Tagesbericht ausfüllen": "Complete at least one daily report",
  "Bitte zuerst einen Postgres-Host anlegen.": "Add a PostgreSQL host first.",
  "Browser-Skripte ansehen, bearbeiten und ausführen.": "View, edit, and run browser scripts.",
  "Buchen": "Book",
  "Buchungshistorie": "Booking history",
  "Buchungshistorie filtern": "Filter booking history",
  "Bucket": "Bucket",
  "Büro": "Office",
  "CDN/Public Hostname": "CDN/public hostname",
  "Client ID": "Client ID",
  "Client-Skripte": "Client scripts",
  "Credentials rotieren": "Rotate credentials",
  "Ctrl K": "Ctrl K",
  "Custom Endpoint": "Custom endpoint",
  "Daily": "Daily",
  "Das Skript": "The script",
  "Dashboard": "Dashboard",
  "Datei": "File",
  "Datei konnte nicht gelesen werden": "File could not be read",
  "Dateien hochladen": "Upload files",
  "Datenbank": "Database",
  "Datenbank erstellen": "Create database",
  "Datenbank erstellt. Zugangsdaten:": "Database created. Credentials:",
  "Datenbank konnte nicht erstellt werden": "Database could not be created",
  "Datenbanken": "Databases",
  "Datenbanken konnten nicht geladen werden:": "Databases could not be loaded:",
  "Datenbankname": "Database name",
  "Datenblatt": "Data sheet",
  "Datenblatt konnte nicht erstellt werden:": "Data sheet could not be created:",
  "Datenzugriff:": "Data access:",
  "Datum": "Date",
  "Datum ist ungültig.": "The date is invalid.",
  "Datum und Uhrzeit sind ungültig.": "The date and time are invalid.",
  "Deaktivieren": "Disable",
  "deaktiviert": "disabled",
  "Deaktiviert": "Disabled",
  "Deaktiviert am": "Disabled on",
  "DeepSeek": "DeepSeek",
  "Defekt": "Broken",
  "Der Benutzer wird im Mandanten": "The user will be created in tenant",
  "Der Bericht gilt immer für Montag bis Sonntag der gewählten Kalenderwoche.": "The report always covers Monday through Sunday of the selected calendar week.",
  "Der Berichtstag darf nicht in der Zukunft liegen.": "The report date cannot be in the future.",
  "Die Gemeinkosten werden historisch gespeichert und gelten immer ab dem gewählten Stichtag um 00:00 Uhr. Ein neuer Eintrag überschreibt keine alten Werte, sondern ergänzt die Historie für spätere Buchungen. Die Berechnung erfolgt je betroffener Kostenposition nach der Formel": "Overhead costs are stored historically and apply from midnight on the selected effective date. A new entry does not overwrite older values; it extends the history for later bookings. Each affected cost item is calculated using this formula",
  "Die PDF konnte nicht erstellt werden.": "The PDF could not be created.",
  "die Rolle": "the role",
  "Die Umbuchung setzt einen neuen Verantwortlichen voraus. Das Projekt kann bei Bedarf mitgeführt werden.": "A transfer requires a new responsible person. The project can be retained if needed.",
  "Die Woche beginnt am Montag. Nur ausgewählte und ausgefüllte Tage werden erstellt.": "The week starts on Monday. Only selected days with completed fields will be created.",
  "Diese Aktion kann nicht rückgängig gemacht werden.": "This action cannot be undone.",
  "Dieser Vermerk wird dauerhaft gelöscht.": "This note will be permanently deleted.",
  "Dokumentation": "Documentation",
  "Download": "Download",
  "Download URL TTL (Sekunden)": "Download URL TTL (seconds)",
  "Download-URL konnte nicht erstellt werden": "Download URL could not be created",
  "Dropdown": "Dropdown",
  "Du siehst deine eigenen Einsätze.": "You can see your own assignments.",
  "Durch die Deaktivierung verliert der betreffende Benutzer mit sofortiger Wirkung die Fähigkeit, sich am System anzumelden.": "Disabling the user immediately prevents them from signing in.",
  "DWG Viewer": "DWG viewer",
  "E-Mail": "Email",
  "E-Mail importieren": "Import email",
  "Echter Einkauf?": "Actual purchase?",
  "Effektiv am": "Effective on",
  "Eingabe": "Input",
  "Einheit": "Unit",
  "Einheit entfernen": "Remove unit",
  "Einkauf": "Purchasing",
  "Einsatz bearbeiten": "Edit assignment",
  "Einsatz hinzufügen": "Add assignment",
  "Einsatz löschen": "Delete assignment",
  "Einsatz planen": "Plan assignment",
  "Einsatzplanung": "Resource planning",
  "Einsatzplanung öffnen": "Open resource planning",
  "Eintrag": "Entry",
  "Eintrag entfernen": "Remove entry",
  "Eintragen": "Add",
  "Einzutragende Tage": "Days to create",
  "Endgültig löschen": "Delete permanently",
  "Endpoint": "Endpoint",
  "Entfernen": "Remove",
  "Entfernt": "Removed",
  "Entschieden am": "Decided on",
  "Entsperren": "Unlock",
  "Erfasse gelieferte Produkte mit Menge und Einheit.": "Record delivered products with quantity and unit.",
  "Erfasst": "Recorded",
  "Erfasst am": "Recorded on",
  "erhält im Mandanten": "will receive the role in tenant",
  "Erlaubt: [a-z][a-z0-9_]{0,62}": "Allowed: [a-z][a-z0-9_]{0,62}",
  "Erstellen": "Create",
  "Erstellt": "Created",
  "Erstellt am": "Created on",
  "erstellt und erhält automatisch die Rolle": "and automatically receives the role",
  "erstellt. Initiales Passwort:": "created. Initial password:",
  "Es läuft bereits ein Skript.": "A script is already running.",
  "Es werden alle Lieferscheine des Projekts im ausgewählten Zeitraum konsolidiert.": "All delivery notes for the project in the selected period will be consolidated.",
  "Es werden alle Regieberichte des Projekts exportiert. Jeder Bericht wird in einem eigenen Tabellenblatt mit Stundenmatrix je Mitarbeiter und Wochentag abgelegt.": "All time-and-material reports for the project will be exported. Each report is placed in a separate worksheet with an hours matrix by employee and weekday.",
  "Es werden alle Regieberichte des Projekts in einer PDF-Datei exportiert. Jeder Bericht umfasst eine Kalenderwoche, startet auf einer neuen Seite und endet mit Signaturfeldern fur Bauleiter und Bauherr.": "All time-and-material reports for the project will be exported to one PDF. Each report covers a calendar week, starts on a new page, and ends with signature fields for the site manager and client.",
  "Es werden alle vorhandenen Bauwochenberichte des Projekts exportiert, nach Kalenderwoche aufsteigend.": "All weekly construction reports for the project will be exported in ascending calendar-week order.",
  "Es wird geprüft, ob innerhalb dieses Zeitraums eine Inventur erfasst wurde.": "Checks whether an inventory entry was recorded during this period.",
  "EUR": "EUR",
  "Excel": "Excel",
  "Exportieren": "Export",
  "Extern": "External",
  "Fehler": "Errors",
  "Fehlerberichte konnten nicht geladen werden:": "Error reports could not be loaded:",
  "Fehlgeschlagen": "Failed",
  "Fertig": "Complete",
  "Filter": "Filter",
  "Filter ändern": "Change filter",
  "Filter anwenden": "Apply filter",
  "Filter aus": "Disable filter",
  "Filteroptionen konnten nicht geladen werden:": "Filter options could not be loaded:",
  "Firma": "Company",
  "Firmenname": "Company name",
  "Fixiert": "Pinned",
  "Fork": "Fork",
  "Fork aus Backup fehlgeschlagen": "Fork from backup failed",
  "Fork erstellen": "Create fork",
  "Fork erstellt:": "Fork created:",
  "Fortsetzen": "Resume",
  "Foto": "Photo",
  "Foto-Aktion fehlgeschlagen:": "Photo action failed:",
  "Fotos": "Photos",
  "Fotos hinzufügen": "Add photos",
  "Fotos werden hochgeladen...": "Uploading photos...",
  "Freigeben": "Approve",
  "Für": "A new password for",
  "Für die Auswahl sind aktuell keine Download-Links verfügbar.": "No download links are currently available for the selection.",
  "Für diese DWG-Datei ist aktuell kein Download-Link verfügbar.": "No download link is currently available for this DWG file.",
  "Für dieses Bild konnte keine Vorschau geladen werden.": "A preview could not be loaded for this image.",
  "Für dieses Projekt sind keine Bautagesberichte vorhanden": "No daily construction reports are available for this project",
  "Fur dieses Projekt sind keine Regieberichte vorhanden": "No time-and-material reports are available for this project",
  "Geändert am": "Changed on",
  "Gebucht": "Booked",
  "Gelöscht": "Deleted",
  "Gemeinkosten": "Overhead costs",
  "Gemeinkosten verwalten": "Manage overhead costs",
  "Genehmigt": "Approved",
  "Gesamt": "Total",
  "Gesamtpreis (EUR)": "Total price (EUR)",
  "Gesperrt": "Blocked",
  "Gewinn/Verlust": "Profit/loss",
  "Gewinn/Verlust (absolut)": "Profit/loss (absolute)",
  "Gewinn/Verlust (relativ)": "Profit/loss (relative)",
  "Gibt es wichtige Details zu dieser Buchung, die dokumentiert werden sollen?": "Are there important details about this booking that should be recorded?",
  "Global Admin": "Global admin",
  "Global Admin Login": "Global admin sign-in",
  "Global Admin Passwort": "Global admin password",
  "Global Admin: Datenbankverwaltung": "Global admin: database management",
  "Global Admin: Tenants": "Global admin: tenants",
  "Globale Zuschläge und Gemeinkosten bearbeiten.": "Manage global markups and overhead costs.",
  "Größe": "Size",
  "Grund": "Reason",
  "Grund fehlt.": "A reason is required.",
  "Gültig ab": "Effective from",
  "Händler": "Vendors",
  "Händler bearbeiten": "Edit vendor",
  "Händler erstellen": "Create vendor",
  "Händler löschen": "Delete vendor",
  "Häufige Fragen": "Frequently asked questions",
  "Herausgeber": "Issued by",
  "Hersteller": "Manufacturer",
  "Herunterladen": "Download",
  "Hinweis": "Note",
  "Hinweise wie Lieferant, Baustellenbereich oder Besonderheiten.": "Add details such as the supplier, site area, or special circumstances.",
  "Hinzufügen": "Add",
  "Historie": "History",
  "Historische Produktpreise und Bezugspreise.": "Historical product and purchase prices.",
  "Host": "Host",
  "Host hinzufügen": "Add host",
  "Host konnte nicht erstellt werden": "Host could not be created",
  "Host konnte nicht gelöscht werden": "Host could not be deleted",
  "Host speichern": "Save host",
  "Hosts konnten nicht geladen werden:": "Hosts could not be loaded:",
  "Ich habe verstanden, dass diese Aktion nicht rückgängig gemacht werden kann.": "I understand that this action cannot be undone.",
  "Ich habe verstanden, dass dieser Benutzer danach keinen global administrierbaren Mandantenzugang mehr hat.": "I understand that this user will no longer have globally managed tenant access.",
  "Im ausgewahlten Zeitraum sind keine Lieferscheine vorhanden": "No delivery notes are available for the selected period",
  "Inaktiv": "Inactive",
  "Inhalt": "Contents",
  "Inhaltsverzeichnis": "Table of contents",
  "Intern": "Internal",
  "Interne Werkzeugnummer für Suche, Listen und Zuordnung.": "Internal tool number used for search, lists, and assignments.",
  "Invalid day": "Invalid day",
  "Invalid week": "Invalid week",
  "Inventur": "Inventory",
  "Inventur aufzeichnen": "Record inventory",
  "Inventurübersicht": "Inventory overview",
  "Inventurzeitraum setzen": "Set inventory period",
  "Join Discord": "Join Discord",
  "Kategorie": "Category",
  "Kategorien": "Categories",
  "Kategorien bearbeiten": "Edit categories",
  "Kaufpreis (EUR)": "Purchase price (EUR)",
  "Kein Admin": "Not an admin",
  "Kein Einsatz": "No assignment",
  "Kein passender Artikel gefunden.": "No matching article found.",
  "Kein Status": "No status",
  "Keine Änderungen.": "No changes.",
  "Keine Benutzer vorhanden.": "No users available.",
  "Keine Daten vorhanden.": "No data available.",
  "Keine Daten zum Bautagesbericht verfügbar.": "No daily construction report data available.",
  "Keine Daten zum Bauwochenbericht verfügbar.": "No weekly construction report data available.",
  "Keine Daten zum Lieferschein verfügbar.": "No delivery-note data available.",
  "Keine Daten zum Regiebericht verfugbar.": "No time-and-material report data available.",
  "Keine Einsätze im gewählten Zeitraum.": "No assignments in the selected period.",
  "Keine Inventurdaten verfügbar.": "No inventory data available.",
  "Keine Kosteninformationen verfügbar.": "No cost information available.",
  "Keine Passkeys vorhanden.": "No passkeys added.",
  "Keine Projektdaten verfügbar.": "No project data available.",
  "Keine Projekte für die aktuellen Filter.": "No projects match the current filters.",
  "Keine Rechte passen zur Suche.": "No permissions match the search.",
  "Keine Treffer.": "No results.",
  "Keine Vorschau": "No preview",
  "Key Prefix": "Key prefix",
  "Kleinbuchstaben, Ziffern, Punkt/Bindestrich/Unterstrich": "Lowercase letters, digits, dot, hyphen, and underscore",
  "Kommentar": "Comment",
  "Kommentar:": "Comment:",
  "Konstante": "Constant",
  "Konstante (EUR)": "Constant (EUR)",
  "Kontakt": "Contact",
  "Kontakt bearbeiten": "Edit contact",
  "Kontakt erstellen": "Create contact",
  "Kontakt löschen": "Delete contact",
  "Kontakt-E-Mail": "Contact email",
  "Kontakte": "Contacts",
  "Kontaktpersonen, Telefonnummern und E-Mail-Adressen.": "Contact people, phone numbers, and email addresses.",
  "Kopiert von:": "Copied from:",
  "Kosten": "Costs",
  "Kosten pro Stunde (EUR)": "Hourly cost (EUR)",
  "Kostenbereiche": "Cost categories",
  "Kostenübersicht": "Cost overview",
  "Kostenübersicht konnte nicht geladen werden:": "Cost overview could not be loaded:",
  "Kostenübersicht öffnen": "Open cost overview",
  "Kunde": "Customer",
  "Kunde bearbeiten": "Edit customer",
  "Kunde erstellen": "Create customer",
  "Kunde für Zuordnung in Auswertungen und Exporten.": "Customer used for reports and exports.",
  "Kunde löschen": "Delete customer",
  "Kunden": "Customers",
  "Kundenstamm und Kundendaten.": "Customer catalog and customer data.",
  "Kurze Einstiege, danach ausführliche Kapitel zu Begriffen und Abläufen.": "Short introductions followed by detailed chapters on terms and workflows.",
  "Kurzfassung": "Summary",
  "Lädt...": "Loading...",
  "Lager": "Warehouse",
  "Land": "Country",
  "Land/Staat": "Country",
  "Language | Settings": "Language | Settings",
  "Läuft": "Running",
  "Leer lassen für automatische Vergabe": "Leave blank to generate automatically",
  "Lesen": "Read",
  "Letzte Inventur": "Last inventory",
  "Letzte Inventur am": "Last inventory on",
  "Letzter Verantwortlicher": "Last responsible person",
  "Lieferanten/Händler für Produkte.": "Suppliers and vendors for products.",
  "Lieferschein": "Delivery note",
  "Lieferschein bearbeiten": "Edit delivery note",
  "Lieferschein erfassen": "Record delivery note",
  "Lieferschein löschen": "Delete delivery note",
  "Lieferschein schreiben": "Create delivery note",
  "Lieferscheine": "Delivery notes",
  "Lieferscheine als Excel exportieren": "Export delivery notes as Excel",
  "Lieferscheine Excel (Zeitraum)": "Delivery notes: Excel (period)",
  "LLM": "LLM",
  "LLM verwenden": "Use LLM",
  "LLM-Verbrauch im laufenden Monat": "LLM usage this month",
  "Logo hochladen": "Upload logo",
  "Logo-Upload konnte nicht vorbereitet werden.": "Logo upload could not be prepared.",
  "Löschen": "Delete",
  "löschen oder endgültig entfernen. Separat vergeben.": "delete or permanently remove. Granted separately.",
  "manage:toolTrackings": "manage:toolTrackings",
  "Mandant": "Tenant",
  "Mandant erstellen": "Create tenant",
  "Mandant erstellt. Initiales Admin-Passwort:": "Tenant created. Initial admin password:",
  "Mandanten": "Tenants",
  "Mandanten konnten nicht geladen werden:": "Tenants could not be loaded:",
  "Mandanten-Details konnten nicht geladen werden:": "Tenant details could not be loaded:",
  "Mandantenname": "Tenant name",
  "Marke": "Brand",
  "Material- und Produktstamm.": "Material and product catalog.",
  "Materiallieferung für Projekt dokumentieren.": "Record a material delivery for a project.",
  "Materiallieferungen auf Projekte erfassen und prüfen.": "Record and review material deliveries for projects.",
  "Mehrere Ansprechpartner können hinterlegt werden.": "You can add multiple contact people.",
  "Mehrere Bautagesberichte für Kalenderwoche erfassen.": "Create multiple daily construction reports for a calendar week.",
  "Meldung": "Message",
  "Menge": "Quantity",
  "Mit Passkey anmelden": "Sign in with passkey",
  "Mit welchem Projekt ist diese Buchung verknüpft?": "Which project is this booking associated with?",
  "Mitarbeiter": "Employee",
  "mittlerer EP": "average unit price",
  "Modell": "Model",
  "Modellbezeichnung oder ergänzende Typangabe.": "Model name or additional type information.",
  "Monatliche Tokenquote": "Monthly token quota",
  "Monthly": "Monthly",
  "Nachname": "Last name",
  "Nachunternehmer-Arbeitszeit": "Subcontractor work hours",
  "Name": "Name",
  "Name des Buckets für Projektdateien": "Bucket name for project files",
  "Namen importieren": "Import names",
  "Neu": "New",
  "Neue Datenbank": "New database",
  "Neue Kontaktperson anlegen.": "Add a contact person.",
  "Neuen Kundenstamm anlegen.": "Add a customer to the customer catalog.",
  "Neuen Mandanten anlegen": "Create tenant",
  "Neuen Produkt-Händler anlegen.": "Add a product vendor.",
  "Neuer Verantwortlicher": "New responsible person",
  "Neues Benutzerkonto anlegen.": "Create a user account.",
  "Neues Material oder Produkt anlegen.": "Add a material or product.",
  "Neues Passwort": "New password",
  "Neues Projekt": "New project",
  "Neues Projekt im Projektstamm anlegen.": "Add a project to the project catalog.",
  "Neues Werkzeug im Werkzeugstamm anlegen.": "Add a tool to the tool catalog.",
  "Nicht Archiviert": "Not archived",
  "Nicht Archviert": "Not archived",
  "Nicht ausgewählt": "Not selected",
  "Niederschlag (mm)": "Precipitation (mm)",
  "Noch kein Organisationslogo verfügbar.": "No organization logo available.",
  "Noch kein Verbrauch in diesem Monat.": "No usage recorded this month.",
  "Noch keine Aktivität sichtbar.": "No activity available yet.",
  "Noch keine Aktivität vorhanden.": "No activity available yet.",
  "Noch keine Projektanhänge vorhanden.": "No project attachments yet.",
  "Noch keine Skripte.": "No scripts yet.",
  "Notiere Zustand, Fehlteile oder besondere Auffälligkeiten der Inventur.": "Record the condition, missing parts, or anything unusual found during inventory.",
  "Notiz": "Note",
  "Nummer": "Number",
  "Nummer automatisch vorschlagen": "Suggest a number automatically",
  "Nummer, Bezeichnung und Basiseinheit definieren den Produktstamm für Auswertungen und Lieferscheine.": "Number, name, and base unit define the product record used in reports and delivery notes.",
  "Nur Kleinbuchstaben, Ziffern und Unterstrich": "Lowercase letters, digits, and underscores only",
  "Nur Lesen": "Read only",
  "Nutzername": "Username",
  "Nutzungskosten pro Tag (EUR)": "Usage cost per day (EUR)",
  "Object ID": "Object ID",
  "Objektspeicher (S3 kompatibel)": "Object storage (S3-compatible)",
  "Objektspeicher aktivieren": "Enable object storage",
  "Offen": "Open",
  "OpenAI": "OpenAI",
  "OpenAI-kompatibel": "OpenAI-compatible",
  "Organisation": "Organization",
  "Organisationslogo": "Organization logo",
  "Original öffnen": "Open original",
  "originale Kosten * relativer Faktor + Konstante": "original cost × relative factor + constant",
  "Passkey": "Passkey",
  "Passkey entfernen": "Remove passkey",
  "Passkey hinzufügen": "Add passkey",
  "Passkey-Anmeldung fehlgeschlagen.": "Passkey sign-in failed.",
  "Passkey-Anmeldung konnte nicht gestartet werden.": "Passkey sign-in could not be started.",
  "Passkey-Anmeldung wurde abgebrochen.": "Passkey sign-in was cancelled.",
  "Passkey-Erstellung wurde abgebrochen.": "Passkey creation was cancelled.",
  "Passkey-Registrierung konnte nicht gestartet werden.": "Passkey registration could not be started.",
  "Passkeys | Einstellungen": "Passkeys | Settings",
  "Passkeys konnten nicht geladen werden.": "Passkeys could not be loaded.",
  "Passkeys werden von diesem Browser nicht unterstützt.": "This browser does not support passkeys.",
  "Passwort": "Password",
  "Passwort | Einstellungen": "Password | Settings",
  "Passwort bestätigen": "Confirm password",
  "Passwort für": "Password for",
  "Passwort setzen": "Set password",
  "Passwort wiederholen": "Repeat password",
  "Passwörter stimmen nicht überein.": "The passwords do not match.",
  "Path-Style URLs erzwingen": "Force path-style URLs",
  "PDF": "PDF",
  "PDF (wochenweise)": "PDF (by week)",
  "PDF wird erstellt...": "Creating PDF...",
  "PDF-Export fehlgeschlagen:": "PDF export failed:",
  "PDF: eine Datei mit Seitenumbruch nach jeder Woche. Excel: eine Arbeitsmappe mit einem Tabellenblatt je Woche.": "PDF: one file with a page break after each week. Excel: one workbook with a worksheet for each week.",
  "Personal": "Staff",
  "Pflege hier Stammdaten und Einheiten für korrekte Mengen- und Kostenberechnungen.": "Maintain master data and units here so quantities and costs are calculated correctly.",
  "Planen": "Plan",
  "PLZ": "Postcode",
  "Port": "Port",
  "Postgres-Host hinzufügen": "Add PostgreSQL host",
  "Postgres-Hosts": "PostgreSQL hosts",
  "Postgres-Verbindung": "PostgreSQL connection",
  "Postleitzahl": "Postcode",
  "Preis": "Price",
  "Preis pro Einheit": "Price per unit",
  "Preis verzeichnen": "Record price",
  "Preisentwicklung": "Price history",
  "Pro Eintrag einen Mitarbeiter und die geleisteten Stunden erfassen.": "Add one employee and their hours per entry.",
  "Pro Eintrag Tag, Mitarbeiter und Stunden der ausgewählten Woche erfassen.": "Add the day, employee, and hours for the selected week in each entry.",
  "Pro Eintrag Tag, Mitarbeiter und Stunden der gewählten Woche erfassen.": "Add the day, employee, and hours for the selected week in each entry.",
  "Problem melden": "Report a problem",
  "Produkt": "Product",
  "Produkt bearbeiten": "Edit product",
  "Produkt erstellen": "Create product",
  "Produkt löschen": "Delete product",
  "Produkte": "Products",
  "Produkte filtern": "Filter products",
  "Produkte, Händler, Preise und Lieferscheine pflegen.": "Maintain products, vendors, prices, and delivery notes.",
  "Produktpreise": "Product prices",
  "Projekt": "Project",
  "Projekt bearbeiten": "Edit project",
  "Projekt erstellen": "Create project",
  "Projekt ist bei bestehenden Berichten fix. Der Tag kann geändert werden.": "The project is fixed for existing reports. The date can be changed.",
  "Projekt ist seit dem": "Project has been",
  "Projekt löschen": "Delete project",
  "Projekt muss ausgewählt sein.": "Select a project.",
  "Projektdaten": "Project data",
  "Projekte": "Projects",
  "Projekte planen, Berichte erfassen, Lieferscheine prüfen, Kosten sehen.": "Plan projects, record reports, review delivery notes, and view costs.",
  "Projektkosten, Lieferscheine und Arbeitszeiten prüfen.": "Review project costs, delivery notes, and work hours.",
  "Projektkostenbericht": "Project cost report",
  "Projektkostenbericht Wochenweise": "Project cost report by week",
  "Projektleiter": "Project manager",
  "Projektstammdaten, Status, Verantwortliche und Kostenbasis.": "Project master data, status, responsibilities, and cost basis.",
  "Projektzuordnung ist fix; hier wird nur zur Einordnung angezeigt.": "The project assignment is fixed and shown here for context.",
  "Projektzuweisungen und Abwesenheiten planen.": "Plan project assignments and absences.",
  "proposal.openContact": "proposal.openContact",
  "proposal.openCustomer": "proposal.openCustomer",
  "proposal.openDailyReports": "proposal.openDailyReports",
  "proposal.openDeliveryNote": "proposal.openDeliveryNote",
  "proposal.openDeployments": "proposal.openDeployments",
  "proposal.openInventory": "proposal.openInventory",
  "proposal.openProduct": "proposal.openProduct",
  "proposal.openProject": "proposal.openProject",
  "proposal.openProjectCosts": "proposal.openProjectCosts",
  "proposal.openRegieReport": "proposal.openRegieReport",
  "proposal.openTool": "proposal.openTool",
  "proposal.openVacations": "proposal.openVacations",
  "Provider": "Provider",
  "Provider / Modell": "Provider / model",
  "Public Base URL": "Public base URL",
  "Quelle": "Source",
  "React Router Docs": "React Router docs",
  "Rechnungssumme": "Invoice total",
  "Rechnungssumme (EUR)": "Invoice total (EUR)",
  "Rechnungssummen": "Invoice totals",
  "Rechte suchen": "Search permissions",
  "Rechte von Benutzer kopieren": "Copy permissions from user",
  "Rechte werden geladen ...": "Loading permissions ...",
  "Regiebericht": "Time-and-material report",
  "Regiebericht bearbeiten": "Edit time-and-material report",
  "Regiebericht erstellen": "Create time-and-material report",
  "Regiebericht löschen": "Delete time-and-material report",
  "Regieberichte": "Time-and-material reports",
  "Regieberichte als Excel exportieren": "Export time-and-material reports as Excel",
  "Regieberichte als PDF exportieren": "Export time-and-material reports as PDF",
  "Regieberichte Excel": "Time-and-material reports: Excel",
  "Regieberichte PDF": "Time-and-material reports: PDF",
  "Regieleistungen mit Arbeitszeit, Material und Sonderpositionen.": "Time-and-material work with hours, materials, and special items.",
  "Region": "Region",
  "Relativer Faktor": "Relative factor",
  "Relativer Faktor in % (z.B. 20)": "Relative factor in % (for example, 20)",
  "Restore": "Restore",
  "Restore aus Upload-Backup fehlgeschlagen": "Restore from uploaded backup failed",
  "Restore fehlgeschlagen": "Restore failed",
  "Retention": "Retention",
  "Retention bearbeiten": "Edit retention",
  "Retention konnte nicht aktualisiert werden": "Retention could not be updated",
  "Rolle": "Role",
  "Rollen setzen": "Set roles",
  "Schließen": "Close",
  "Schnellaktionen": "Quick actions",
  "Secret Access Key": "Secret Access Key",
  "sehen, suchen, öffnen. Keine Änderungen.": "view, search, and open. No changes.",
  "Session Token": "Session Token",
  "Skript erstellen": "Create script",
  "Skript konnte nicht erstellt werden.": "Script could not be created.",
  "Skript konnte nicht gespeichert werden.": "Script could not be saved.",
  "Skript löschen": "Delete script",
  "Skript nicht gefunden.": "Script not found.",
  "Skripte": "Scripts",
  "Skriptvorschau": "Script preview",
  "sleep erwartet nicht-negative Millisekunden.": "sleep expects a non-negative number of milliseconds.",
  "Soll": "Should",
  "Soll die": "Should the",
  "Sonderposten": "Special items",
  "Sonderposten entfernen": "Remove special item",
  "Sonderposten sind zusätzliche Leistungen oder Materialien, die nicht als Produktstamm vorhanden sind.": "Special items are additional services or materials that are not in the product catalog.",
  "sortsys Admin": "sortsys admin",
  "sortsys Global Admin": "sortsys global admin",
  "Speichern": "Save",
  "Sperre löschen": "Delete block",
  "Sperren": "Lock",
  "SSO (Microsoft Entra ID)": "SSO (Microsoft Entra ID)",
  "SSO aktivieren": "Enable SSO",
  "Stadt": "City",
  "Stammdaten pflegen, Material und Berichte erfassen, ohne Löschrechte.": "Maintain master data and record materials and reports without delete permissions.",
  "Standard entfernen": "Remove default",
  "Standard speichern": "Save default",
  "Standard-Vorgesetzter": "Default supervisor",
  "Standard-Vorgesetzter:": "Default supervisor:",
  "Status": "Status",
  "Straße & Hausnummer": "Street and house number",
  "Strasse und Hausnummer": "Street and house number",
  "Stunden": "Hours",
  "Stunden ausblenden": "Hide hours",
  "Subunternehmer": "Subcontractor",
  "Suchen": "Search",
  "Tabellenexport": "Table export",
  "Tag": "Day",
  "Tage": "Days",
  "Tagesberichte": "Daily reports",
  "Tagessatz für interne Kostenberechnungen und Berichte.": "Daily rate used for internal cost calculations and reports.",
  "Tagesweise Baustellen-Dokumentation mit Wetter und Arbeitszeiten.": "Daily site documentation with weather and work hours.",
  "Täglichen Baustellenstand mit Zeiten und Wetter erfassen.": "Record daily site progress, work hours, and weather.",
  "Telefon": "Phone",
  "Temperatur (°C)": "Temperature (°C)",
  "Tenant ID": "Tenant ID",
  "Tippe > für Befehle, sonst Suche": "Type > for commands, or enter a search term",
  "Titel": "Title",
  "Token": "Tokens",
  "Typ": "Type",
  "über": "for",
  "Übersicht": "Overview",
  "Umbuchen": "Transfer",
  "Umbuchen auf": "Transfer to",
  "Umbuchungsanfrage": "Transfer request",
  "Umbuchungsanfragen": "Transfer requests",
  "Unbegrenzt": "Unlimited",
  "Unbekannter Benutzer": "Unknown user",
  "Unbekanntes Projekt": "Unknown project",
  "Ungültige Passkey-Antwort.": "Invalid passkey response.",
  "Ungültige Woche": "Invalid week",
  "Ungültiger Datenbankname. Erlaubt: [a-z][a-z0-9_]{0,62}": "Invalid database name. Allowed: [a-z][a-z0-9_]{0,62}",
  "Ungültiger Username. Erlaubt: [a-z][a-z0-9_]{0,62}": "Invalid username. Allowed: [a-z][a-z0-9_]{0,62}",
  "Ungültiger Wochentag": "Invalid weekday",
  "Ungültiges Dateiformat. Erlaubt sind PNG, JPG/JPEG und WEBP.": "Invalid file format. Allowed formats are PNG, JPG/JPEG, and WEBP.",
  "Ungültiges Datum": "Invalid date",
  "Unterbrechung bearbeiten": "Edit interruption",
  "Unterbrechung eintragen": "Add interruption",
  "Unterbrechungen erscheinen in der Einsatzplanung und markieren betroffene Einsätze.": "Interruptions appear in resource planning and mark affected assignments.",
  "Upload konnte nicht vorbereitet werden.": "Upload could not be prepared.",
  "Upload läuft...": "Uploading...",
  "Upload URL TTL (Sekunden)": "Upload URL TTL (seconds)",
  "Urlaub": "Leave",
  "Urlaub ablehnen": "Reject leave",
  "Urlaub beantragen": "Request leave",
  "Urlaub eintragen": "Add leave",
  "Urlaube beantragen, einsehen und genehmigen.": "Request, view, and approve leave.",
  "Urlaube konnten nicht geladen werden:": "Leave entries could not be loaded:",
  "User-Agent:": "User agent:",
  "Username": "Username",
  "Username importieren": "Import username",
  "useSessionInfo must be used within a SessionInfoProvider": "useSessionInfo must be used within a SessionInfoProvider",
  "Verantwortlich": "Responsible",
  "Verantwortlicher": "Responsible person",
  "Verantwortlicher Projektleiter": "Responsible project manager",
  "Verbindung": "Connection",
  "Verbrauch im laufenden Monat": "Usage this month",
  "Verbrauchte Produkte inklusive Menge und Einheit dokumentieren.": "Record consumed products with their quantity and unit.",
  "Verfügbar": "Available",
  "Vergeben": "Grant",
  "verliert im Mandanten": "will lose the role in tenant",
  "Vermerk": "Note",
  "Vermerk bearbeiten": "Edit note",
  "Vermerk erstellen": "Create note",
  "Vermerk löschen": "Delete note",
  "Vermerke": "Notes",
  "Vermerke konnten nicht geladen werden:": "Notes could not be loaded:",
  "Vertrag": "Contract",
  "Verwende einen klaren Projektnamen, damit das Projekt in Listen schnell gefunden wird.": "Use a clear project name so it is easy to find in lists.",
  "von": "of",
  "Von": "From",
  "Von (Datum)": "From (date)",
  "Von (Uhrzeit)": "From (time)",
  "Von darf nicht nach Bis liegen": "From cannot be after To",
  "Von muss vor Bis liegen.": "From must be before To.",
  "Vorgesetzte": "Supervisors",
  "Vorgesetzten entfernen": "Remove supervisor",
  "Vorgesetzten setzen": "Set supervisor",
  "Vorgesetzter": "Supervisor",
  "Vorlagen": "Templates",
  "Vorname": "First name",
  "Vorname oder Nachname ist erforderlich": "A first or last name is required",
  "Wähle das Projekt, für das der Bautagesbericht erstellt wird.": "Select the project for the daily construction report.",
  "Wähle das Projekt, für das der Bauwochenbericht erstellt wird.": "Select the project for the weekly construction report.",
  "Wähle das Projekt, für das der Regiebericht erstellt wird.": "Select the project for the time-and-material report.",
  "Wähle das Projekt, zu dem der Lieferschein erfasst werden soll.": "Select the project for this delivery note.",
  "Wähle einen beliebigen Tag der Zielwoche; es wird automatisch auf Montag bis Sonntag erweitert.": "Select any day in the target week; the range will automatically expand from Monday through Sunday.",
  "Wann wurde der Auftrag bestätigt bzw. erhalten?": "When was the order confirmed or received?",
  "Weekly": "Weekly",
  "Weiter": "Next",
  "Weiter →": "Next →",
  "Weitere Einheit": "Add unit",
  "Weitere Positionen erfassen, die nicht als Produkt vorhanden sind.": "Add items that are not available as products.",
  "Welche Werkzeuge wurden ausgegeben?": "Which tools were issued?",
  "Wer hat das Werkzeug bzw. die Werkzeuge entgegengenommen?": "Who received the tool or tools?",
  "Wer verantwortet das Projekt übergreifend?": "Who is responsible for the overall project?",
  "Werkzeug": "Tool",
  "Werkzeug bearbeiten": "Edit tool",
  "Werkzeug erstellen": "Create tool",
  "Werkzeug ist seit dem": "Tool has been",
  "Werkzeug löschen": "Delete tool",
  "Werkzeug umbuchen": "Transfer tool",
  "Werkzeugbuchungen": "Tool bookings",
  "Werkzeuge": "Tools",
  "Werkzeuge ausgeben, zurücknehmen oder umbuchen.": "Issue, return, or transfer tools.",
  "Werkzeuge einbuchen": "Book tools",
  "Werkzeuge filtern": "Filter tools",
  "Werkzeuge mit und ohne Inventur im gewählten Zeitraum": "Tools with and without an inventory entry in the selected period",
  "Werkzeuge, Inventur, Materialstamm und Lieferscheine bearbeiten.": "Manage tools, inventory, material master data, and delivery notes.",
  "Werkzeuginventuren ansehen, anlegen und abschließen.": "View, create, and complete tool inventories.",
  "Werkzeugstamm, Verfügbarkeit und Stammdaten.": "Tool catalog, availability, and master data.",
  "Werkzeugumbuchung anfragen": "Request tool transfer",
  "Wetter": "Weather",
  "Wetterangaben helfen bei der späteren Dokumentation.": "Weather details help with later documentation.",
  "Wetterbeschreibung": "Weather description",
  "Wiederherstellen": "Restore",
  "Wind (km/h)": "Wind (km/h)",
  "wird ein neues Passwort erzeugt. Es wird nur einmal angezeigt.": "will receive a new password. It is shown only once.",
  "wird endgültig gelöscht.": "will be permanently deleted.",
  "Wird entfernt...": "Removing...",
  "wirklich entfernen?": "really be removed?",
  "wirklich gelöscht werden?": "really be deleted?",
  "Woche (beliebiger Tag)": "Week (any day)",
  "Wochenweise Kosten": "Weekly costs",
  "Yearly": "Yearly",
  "z. B. eu-central-1 oder us-east-1": "for example, eu-central-1 or us-east-1",
  "z. B. https://s3.example.com": "for example, https://s3.example.com",
  "z. B. Projekt, Lieferschein, Lager, Regie": "for example, project, delivery note, inventory, time-and-material work",
  "z. B. tenants/staging": "for example, tenants/staging",
  "z.B. Projekte, löschen, Urlaub": "for example, projects, delete, leave",
  "Zeilen pro Seite": "Rows per page",
  "Zeilen:": "Rows:",
  "Zeit": "Time",
  "Zeitraum in Tagen": "Period in days",
  "Zugangsdaten konnten nicht rotiert werden": "Credentials could not be rotated",
  "Zugangsdaten rotiert. Neuer Login:": "Credentials rotated. New login:",
  "Zuletzt besucht": "Recently visited",
  "Zuletzt geändert": "Recently changed",
  "Zur Dokumentation": "Back to documentation",
  "Zurück": "Back",
  "Zurückbuchen": "Return",
  "zurückgesetzt:": "reset:",
  "Zurücksetzen": "Reset",
  "Zusammenfassung": "Summary",
  "Zusatzinfo zum Einsatz, z. B. Materialfahrt oder Baustellenwechsel.": "Additional assignment details, such as a material run or site change.",
  "Zusatzleistungen mit Zeiten, Material und Sonderpositionen erfassen.": "Record additional work, hours, materials, and special items.",
  "Zyklen oder verwaiste Einträge": "Cycles or orphaned entries",
  "Zyklus erkannt": "Cycle detected",
  "Datum darf nicht in der Zukunft liegen": "Date cannot be in the future",
  "Keine Beschreibung": "No description",
  "Unbekannter Fehler": "Unknown error",
  "Skript wurde nach 120 Sekunden beendet.": "Script stopped after 120 seconds.",
  "Datum und Unterschrift": "Date and signature",
  "Passwort gespeichert.": "Password saved.",
  "Vorschau wird erstellt": "Generating preview",
  "Dateien konnten nicht entfernt werden.": "Files could not be removed.",
  "Mit freien Zeilen": "Include empty rows",
  "Nur mit Einsatz": "Assignments only",
  "Gewinn/Verlust kann nicht berechnet werden, da Rechnungssummen fehlen.": "Profit/loss cannot be calculated because invoice totals are missing.",
  "Unbekannter Fehler beim PDF-Export.": "Unknown error while exporting the PDF.",
  "Client-Skripte konnten nicht geladen werden.": "Client scripts could not be loaded.",
  "Client-Skript konnte nicht geladen werden.": "Client script could not be loaded.",
  "Skript gespeichert.": "Script saved.",
  "Fixierung entfernen": "Unpin from dashboard",
  "Auf Dashboard fixieren": "Pin to dashboard",
  "Archivierte-Benutzer": "Archived users",
  "Keine Berechtigung": "No permission",
  "Keine Ansprechpartner hinterlegt.": "No contacts added.",
  "Unbekannter Fehler beim Erstellen des Datenblatts.": "Unknown error while creating the data sheet.",
  "Erstellt von": "Created by",
  "Passkey konnte nicht gespeichert werden.": "Passkey could not be saved.",
  "Passkey gespeichert.": "Passkey saved.",
  "Passkey konnte nicht entfernt werden.": "Passkey could not be removed.",
  "Fotos konnten nicht hochgeladen werden.": "Photos could not be uploaded.",
  "Foto konnte nicht entfernt werden.": "Photo could not be removed.",
  "Keine Inventur": "No inventory",
  "Noch nie inventiert": "Never inventoried",
  "wird am": "will be on",
  "ist seit dem": "has been since",
  "Organisationslogo konnte nicht geladen werden.": "Organization logo could not be loaded.",
  "Organisationslogo wurde erfolgreich aktualisiert.": "Organization logo updated.",
  "Standard-Vorgesetzter konnte nicht entfernt werden.": "Default supervisor could not be removed.",
  "Firmenname konnte nicht gespeichert werden.": "Company name could not be saved.",
  "Standard-Vorgesetzter konnte nicht gespeichert werden.": "Default supervisor could not be saved.",
  "(nur zum Ersetzen)": "(only when replacing)",
  "Mandant konnte nicht erstellt werden": "Tenant could not be created",
  "Admin-Benutzer konnte nicht erstellt werden": "Admin user could not be created",
  "Admin entfernen": "Remove admin",
  "Zum Admin": "Make admin",
  "Arbeit": "Work",
  "Lieferschein Export (Zeitraum)": "Delivery note export (period)",
  "Lohngemeinkosten (interne Arbeitszeit)": "Labour overhead (internal work)",
  "Nachunternehmergemeinkosten (SUB-Arbeitszeit)": "Subcontractor overhead (subcontractor work)",
  "Zeitraum": "Period",
  "Kennzahl": "Metric",
  "Wert": "Value",
  "Export fehlgeschlagen.": "Export failed.",
  "Vorschau fehlgeschlagen": "Preview failed",
  "Datei-Upload fehlgeschlagen.": "File upload failed.",
  "NU-Arbeitszeit": "Subcontractor work",
  "Skript erstellt.": "Script created.",
  "Skript fehlgeschlagen.": "Script failed.",
  "Lieferschein gesamt": "Delivery note total",
  "Beantragt": "Requested",
  "Inventiert": "Inventoried",
  "Kosten pro Std": "Cost per hour",
  "Logo-Upload fehlgeschlagen.": "Logo upload failed.",
  "Anmeldung fehlgeschlagen": "Sign-in failed",
  "Aktion fehlgeschlagen": "Action failed",
};
